### ISSUE TITLE
conver logs to Json

### ISSUE THREAD

**Issue by Cry0k** [zeek/zeek#536] opened 2019-08-11 20:31 UTC
Hi team,

i installed a new zeek instance and i can not locate the file that used to be main.bro where i could change the log type configuration from ascii to json, and it is really critical for me.

if any one could tell me where i can find this file it would be awesome. 
if i am not mistaken i am using zeek version 3.1.0 dev 18

**Comment by timwoj** [comment] 2019-08-12 02:26
You need to load “tuning/json-logs.zeek” somewhere in your configuration. You can either add it to share/bro/policy/tuning/defaults/__load__.zeek or load it from share/bro/site/local.zeek.

Tim

**Comment by Cry0k** [comment] 2019-08-12 07:48
hi tim i donnt have any bro folders on my installation

also in what log i can see the netwrok vrowsings including requests in my previous installetion i saw it under i think http.log but now i cannt find the right log to detect the urls that the user accessed to

**Comment by 0xxon** [comment] 2019-08-12 15:33
Hi Cry0k,

the only thing that should have changed with the switch from bro to zeek is that... the names changed from bro to zeek. I have no clue which main.bro you edited (there are quite a few in the source code) - but it will just be called main.zeek now. 

Apart from that, the comment of Tim is correct - if you are using zeekctl, just edit your local.zeek and add "@load tuning/json-logs.zeek" in there. If you run zeek via the command-line, add "tuning/json-logs.zeek" to the end of the command line.

The names of the log files have not changed, it is still http.log.

Also - since this is not a bug in Zeek, I am going to close this instance. For community support for Zeek, please use our email list zeek@zeek.org, to which you can subscribe at http://mailman.icsi.berkeley.edu/mailman/listinfo/zeek. We reserve issues for discussion of bugs/shortcomings.

I hope thhis helps :)

**Closed by 0xxon** 2019-08-12 15:33 UTC
