### ISSUE TITLE
broker.store.brokerstore-backend-simple-reverse test consistently fails on OS-X

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#1336] opened 2020-12-15 17:17 UTC
The broker.store.brokerstore-backend-simple-reverse test consistently fails on os-x (10.15.7) for me.

I think this behavior started with merging GH-1319.

Test output:

```
[  0%] broker.store.brokerstore-backend-simple-reverse ... failed
  % 'btest-bg-wait 40' failed unexpectedly (exit code 1)
  % cat .stderr
  The following processes did not terminate:

  ZEEKPATH=.:/Users/johanna/bro/master/scripts:/Users/johanna/bro/master/scripts/policy:/Users/johanna/bro/master/scripts/site:/Users/johanna/bro/master/build/scripts:.. CLUSTER_NODE=manager-1 zeek -b -B broker /Users/johanna/bro/master/testing/btest/broker/store/sort-stuff.zeek ../common.zeek ../master.zeek >../master.out
  ZEEKPATH=.:/Users/johanna/bro/master/scripts:/Users/johanna/bro/master/scripts/policy:/Users/johanna/bro/master/scripts/site:/Users/johanna/bro/master/build/scripts:.. CLUSTER_NODE=worker-1 zeek -b -B broker /Users/johanna/bro/master/testing/btest/broker/store/sort-stuff.zeek ../common.zeek ../clone.zeek >../clone.out
  ZEEKPATH=.:/Users/johanna/bro/master/scripts:/Users/johanna/bro/master/scripts/policy:/Users/johanna/bro/master/scripts/site:/Users/johanna/bro/master/build/scripts:.. CLUSTER_NODE=worker-2 zeek -b -B broker /Users/johanna/bro/master/testing/btest/broker/store/sort-stuff.zeek ../common.zeek ../clone2.zeek >../clone2.out

  -----------
  <<< [79617] ZEEKPATH=.:/Users/johanna/bro/master/scripts:/Users/johanna/bro/master/scripts/policy:/Users/johanna/bro/master/scripts/site:/Users/johanna/bro/master/build/scripts:.. CLUSTER_NODE=manager-1 zeek -b -B broker /Users/johanna/bro/master/testing/btest/broker/store/sort-stuff.zeek ../common.zeek ../master.zeek >../master.out
  ./../master.zeek, line 4: Peer added: [id=B246F32A67BA3F30742C4C68411EF5CEF7EED074#79634, network=[address=127.0.0.1, bound_port=52029/tcp]]
  ./../master.zeek, line 4: Peer added: [id=EF7F4A8ECC3F6C7DE25E66244EE1176D0BE8DDBE#79649, network=[address=127.0.0.1, bound_port=52030/tcp]]
  received termination signal
  >>>
  <<< [79632] ZEEKPATH=.:/Users/johanna/bro/master/scripts:/Users/johanna/bro/master/scripts/policy:/Users/johanna/bro/master/scripts/site:/Users/johanna/bro/master/build/scripts:.. CLUSTER_NODE=worker-1 zeek -b -B broker /Users/johanna/bro/master/testing/btest/broker/store/sort-stuff.zeek ../common.zeek ../clone.zeek >../clone.out
  ./../clone.zeek, line 26: Node Up: manager-1
  ./../clone.zeek, line 37: Received announce_masters: {
  s,
  t,
  rt,
  r
  }
  received termination signal
  >>>
  <<< [79647] ZEEKPATH=.:/Users/johanna/bro/master/scripts:/Users/johanna/bro/master/scripts/policy:/Users/johanna/bro/master/scripts/site:/Users/johanna/bro/master/build/scripts:.. CLUSTER_NODE=worker-2 zeek -b -B broker /Users/johanna/bro/master/testing/btest/broker/store/sort-stuff.zeek ../common.zeek ../clone2.zeek >../clone2.out
  ./../clone2.zeek, line 25: Node Up: manager-1
  ./../clone2.zeek, line 12: Received announce_masters: {
  s,
  t,
  rt,
  r
  }
  received termination signal
  >>>

1 of 1 test failed
```

I did not investigate this in more detail yet. Pinging @Neverlord

**Comment by Neverlord** [comment] 2020-12-16 08:54
I couldn't reproduce this yet, but some other tests also fail sporadically:

```
$ cat .tmp/broker.disconnect/.diag 
== File ===============================
receiver got event, 2
peer added, handshake successful
== Diff ===============================
--- /tmp/test-diff.77243.recv2.recv2.out.baseline.tmp	2020-12-16 08:25:55.000000000 +0000
+++ /tmp/test-diff.77243.recv2.recv2.out.tmp	2020-12-16 08:25:55.000000000 +0000
@@ -1,2 +1,2 @@
-peer added, handshake successful
 receiver got event, 2
+peer added, handshake successful
=======================================
```

This boils down to a race during handshake that I've already fixed in the ALM branch. Too bad we didn't get that in for 4.0. 😔

I'll backport the code for making handshakes more robust. Wasn't an easy fix, unfortunately.

**Comment by Neverlord** [comment] 2020-12-16 12:09
The regression I've seen actually comes from https://github.com/zeek/broker/pull/91. Maybe I can restore the previous behavior without backporting the new handshake FSM.

**Comment by Neverlord** [comment] 2020-12-16 18:35
https://github.com/zeek/broker/pull/158 fixes the regression with events arriving out of order. I can still reproduce the error you see with `broker.store.brokerstore-backend-simple-reverse`, but only for release builds.

**Comment by Neverlord** [comment] 2020-12-18 16:36
@0xxon sorry for the wall of text. But please let me outline my understanding of the scripts/tests involved in `broker.store.brokerstore-backend-simple-reverse` to make sure I'm not missing something.

The first clone (`clone.zeek`) writes to some Broker stores in its `dump_tables` event handler. This event triggers from `node_up`. So here's what I don't understand: there is also the event `Broker::announce_masters`. This event gets auto-generated in `base/frameworks/cluster/broker-stores.zeek` from the `peer_added` handler. In the same file, there is a handler for `Broker::announce_masters` that actually creates the local Broker store clones.

The entire setup requires that Zeek fires `node_up` *after* the Broker clones are up and running. However, that's *not* the case:

```
$ cat worker-1/.std*
./../clone.zeek, line 26: Node Up: manager-1
./../clone.zeek, line 36: Received announce_masters: {
s,
t,
rt,
r
}
```

If `node_up` fires before `announce_master`, then I can see in the logs that nothing happens on the Broker side. This seems to make sense, because the Zeek script touches its variables before they are connected to the store master.

So after some digging, `node_up` comes from `hello` in `base/frameworks/cluster/main.zeek` which gets fired from the `Broker::peer_added` handler in the same file. The peer_added handler has priority 10. The high priority actually makes sure that `node_up` always comes before `announce_masters`.

Basically, at this point I'm wondering how this could ever work in the first place. The test seems to work consistently for me with this patch:

```diff
diff --git a/scripts/base/frameworks/cluster/broker-stores.zeek b/scripts/base/frameworks/cluster/broker-stores.zeek
index 04be1fe78..533fa82de 100644
--- a/scripts/base/frameworks/cluster/broker-stores.zeek
+++ b/scripts/base/frameworks/cluster/broker-stores.zeek
@@ -37,7 +37,7 @@ event zeek_init()
        }
 
 # Send the auto masters we created to the newly connected node
-event Broker::peer_added(endpoint: Broker::EndpointInfo, msg: string) &priority=1
+event Broker::peer_added(endpoint: Broker::EndpointInfo, msg: string) &priority=11
        {
        if ( ! Cluster::is_enabled() )
                return;
```

This is just a quick fix to make sure `node_up` fires *after* `announce_master`. However, to me it still makes no sense why the script triggers the store operations from `node_up` in the first place. Shouldn't this happen from `announce_masters` instead? This seems the more natural place for it, at least I understand this handler as "ok, this set of stores is now connected to the remote master: go ahead and use them!". So what am I missing in the picture that makes `node_up` the right place? If it isn't after all, then I think the right patch would be to move `dump_tables` and the polling of `check_all_set` to `announce_master` instead (plus making sure the priorities work out such that user code runs after the Broker setup is done).

**Comment by jsiwek** [comment] 2020-12-21 21:57
> The peer_added handler has priority 10. The high priority actually makes sure that `node_up` always comes before `announce_masters`.
> 
> Basically, at this point I'm wondering how this could ever work in the first place.

Looks like it can depend on a race.

* If the priority 10 `Broker::peer_added` gets processed/received within the same batch of messages as the priority 1: the Zeek event queue contains `Cluster::hello` followed by `Broker::announce_master`.  After the Zeek event queue is flushed, the handler for `Cluster::hello` then adds a `Cluster::node_up` event to the queue.

* If the two `Broker::peer_added` events are processed/received separately, you might see: Zeek event queue contains `Cluster::hello`, Zeek event queue is flushed, `Cluster::node_up` is added to the queue, then the priority 1 `Broker::peer_added` is received and adds `Broker::announce_master` to the queue.

Which of those cases happens depends on process/thread scheduling vagaries.

> The test seems to work consistently for me with this patch:
> 
> ```diff
> diff --git a/scripts/base/frameworks/cluster/broker-stores.zeek b/scripts/base/frameworks/cluster/broker-stores.zeek
> index 04be1fe78..533fa82de 100644
> --- a/scripts/base/frameworks/cluster/broker-stores.zeek
> +++ b/scripts/base/frameworks/cluster/broker-stores.zeek
> @@ -37,7 +37,7 @@ event zeek_init()
>         }
>  
>  # Send the auto masters we created to the newly connected node
> -event Broker::peer_added(endpoint: Broker::EndpointInfo, msg: string) &priority=1
> +event Broker::peer_added(endpoint: Broker::EndpointInfo, msg: string) &priority=11
>         {
>         if ( ! Cluster::is_enabled() )
>                 return;
> ```

That's what I'm thinking, too, (unless tests reveal it's unstable for another reason) if you want to PR it.

> However, to me it still makes no sense why the script triggers the store operations from `node_up` in the first place. Shouldn't this happen from `announce_masters` instead? This seems the more natural place for it, at least I understand this handler as "ok, this set of stores is now connected to the remote master: go ahead and use them!". So what am I missing in the picture that makes `node_up` the right place?

Maybe wouldn't call it the Right place, but still a Likely place where people might do such operations due to it being the more general/abstract option.

The Cluster framework is built on top of the Broker framework and the names of these events are `Broker::announce_masters` and `Cluster::node_up`, so also may be intuitive to expect lower-level Broker setups to have already happened before the Cluster event.

**Comment by 0xxon** [comment] 2020-12-22 16:25
Yup, that makes sense to me too and I agree with the patch.

And - I honestly do not recall at all how I came up with how the events are used in the tests - this was too long ago. To be honest - I assume that there was a fair amount of copy-pasting going on - with me just trying to cover all of the new syntax.

As another addition - I like ``node_up`` as the place to trigger the store operations. The ``announce_masters`` event is only necessary because we don't have ALM yet - and should go away again in the future.

**Comment by 0xxon** [comment] 2020-12-22 16:32
Looking at the source - yup, I probably just missed where node_up is generated and that there is a race condition. Thanks a lot for finding this :)

**Comment by Neverlord** [comment] 2020-12-22 20:20
Ok, thank you two for adding the high-level view!

Since users of the cluster framework shouldn't need to worry about the Broker events and given that `announce_masters` probably becomes obsolete anyway, it seems like just making sure the ordering is correct is the way to go then. I've filed the patch as a PR.

**Closed** 2020-12-23 18:39 UTC
Labels: Area: Broker, Type: Bug :bug:
