### ISSUE TITLE
Broker::__opaque_clone_through_serialization return value for set iterator has Error type

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#1073] opened 2020-07-17 18:01 UTC
This one is esoteric, but gets tickled by the `broker/opaque.zeek` btest.  That winds up calling `Broker::__opaque_clone_through_serialization` a bunch of times.  The call at line 103 (which is for a set iterator) returns a value whose type has a type-tag of `TYPE_ERROR` rather than `TYPE_OPAQUE`.  It's possible that other calls have that property too, but this is the one that triggered an inconsistency check for my branch.

**Comment by jsiwek** [comment] 2020-07-17 18:19
Think this is duplicate of #983 and doesn't look like your branch has the patch from #984 (of course, let me know if you find otherwise).

**Closed by jsiwek** 2020-07-17 18:19 UTC
Labels: Area: Broker, Area: Scripting, Type: Bug :bug:

**Comment by vpax** [comment] 2020-07-17 18:32
Damn, I had search on "opaque_clone" before filing but nothing came up.  Gotta learn how to do that correctly! :-P

Thanks for the quick turnaround, and apologies for not remembering I'd already complained about this.
