### ISSUE TITLE
Failure to iterate through response from record_type_to_vector(), due to hole

### ISSUE THREAD

**Issue by philrz** [zeek/zeek#1763] opened 2021-09-05 18:51 UTC
### Executive Summary

I have a Zeek script [print-types.zeek](https://github.com/brimdata/zeek/blob/master/brim/print-types.zeek) that makes use of [`record_type_to_vector()`](https://github.com/zeek/zeek/blob/0746ef7ecc977a4fad2f0ffa1fe3a9944b94d7f0/src/zeek.bif#L1737-L1753). My script started failing when I made the transition from Zeek v4.0.3 to Zeek 4.1.0. In a [chat on the Zeek public Slack](https://zeekorg.slack.com/archives/CTGDG83B8/p1630632882020800) I confirmed with the Zeek Dev team that this seems to be due to a change how iteration through vectors works, and it appears that change exposed a problem with `record_type_to_vector()`. I've effectively worked around my specific problem for the moment, but at the conclusion of the Slack chat it was suggested I open an issue, so, here it is.

### Details

It's easiest to see the problem by extending the btest [record_type_to_vector.zeek](https://github.com/zeek/zeek/blob/release/4.1/testing/btest/bifs/record_type_to_vector.zeek) and comparing what happens between the two Zeek versions.

On Zeek v4.0.3:

```
$ /usr/local/zeek-4.0.3/bin/zeek -e 'event zeek_init() { local v: vector of string; v[1] = "foo"; v[2] = "bar"; v[4] = "baz"; print v; for (idx in v) { print idx; } for (idx in v) { print v[idx]; } }'
[, foo, bar, , baz]
1
2
4
foo
bar
baz
```

On Zeek v4.1.0:

```
$ /usr/local/zeek-4.1.0/bin/zeek -e 'event zeek_init() { local v: vector of string; v[1] = "foo"; v[2] = "bar"; v[4] = "baz"; print v; for (idx in v) { print idx; } for (idx in v) { print v[idx]; } }'
[, foo, bar, , baz]
0
1
2
3
4
expression error in <command line>, line 1: no such index (v[idx])
fatal error in <command line>, line 3: errors occurred while initializing
```

This shows me two things:

1. Even in Zeek v4.0.3 when it was working, `record_type_to_vector()` was leaving a "hole" as the 0th element of the vector, and it's not clear why. However, in that Zeek rev, iterating through its contents in the `for` loop as I'm doing here skipped the hole, so I never saw any problems from it in the past.

2. In Zeek 4.1.0, now the iterating with `for` causes an attempted access of the "hole", which triggers the failure.

Knowing what I do now, I could make all of my scripts safer about how they access vectors. However, if `record_type_to_vector()` had not been producing the vector with the hole, I'd also not have experienced the failure. In my own local test, I ran an experiment and changed the `Assign(i+1,...` in `record_type_to_vector()` to `Assign(i, ...` and that removed the hole and my script worked as before, so, that may be all there is to fixing it. But I don't claim to understand if there's a reason I'm not seeing for the hole to have been there in the first place.

**Comment by 0xxon** [comment] 2021-09-06 11:11
Since this is a regression we should fix this in a 4.1 dot-release.

**Comment by timwoj** [comment] 2021-09-07 16:18
I asked Vern to pull the above commit out into a separate PR so we can get it merged more easily.

**Comment by timwoj** [comment] 2021-09-07 21:43
Added to the list for 4.1.1.

**Comment by timwoj** [comment] 2021-09-08 19:05
Fixed via https://github.com/zeek/zeek/commit/19cb2df8135af1401e1fbf4c239c91243a9b480c

**Closed by timwoj** 2021-09-08 19:05 UTC
