### ISSUE TITLE
Update btest baselines for new version

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#1307] opened 2020-11-23 10:59 UTC
The newer btest versions record canonified baselines. We should do a full update of all baselines before 4.0

**Comment by ckreibich** [comment] 2020-11-23 17:13
Duplicate of #1302

**Comment by ckreibich** [comment] 2020-11-23 22:49
Folks I'm going over updated baselines and I'm spotting a few things we can improve in our canonifiers. To start with, I'd like to propose this:

```
diff --git i/testing/scripts/diff-remove-timestamps w/testing/scripts/diff-remove-timestamps
index 8ee28c29b..1d4d8286a 100755
--- i/testing/scripts/diff-remove-timestamps
+++ w/testing/scripts/diff-remove-timestamps
@@ -9,5 +9,5 @@ else
    sed="sed -E"
 fi

-$sed 's/(0\.000000)|([0-9]{9,10}\.[0-9]{1,8})/XXXXXXXXXX.XXXXXX/g' | \
+$sed 's/([0-9]{9,10}\.[0-9]{1,8})/XXXXXXXXXX.XXXXXX/g' | \
 $sed 's/^ *#(open|close).(19|20)..-..-..-..-..-..$/#\1 XXXX-XX-XX-XX-XX-XX/g'
```
I.e., simply remove the explicit 0.000000 pattern from the timestamp normalizer.  Attached is a diff that shows you the changes in normalized baselines when we drop this. I'd argue in all cases the changed normalization is better (certainly for things like `8640XXXXXXXXXX.XXXXXX` -> `86400.000000`). If you think the normalizations really should apply to 0.000000 timestamps, we could tighten that pattern to match only at the beginning of the line, or perhaps only if preceded by something not a number. But I think one could argue that Zeek producing zero-timestamps is okay to capture in the baseline.

[changes-without-zeroes-removal.txt.gz](https://github.com/zeek/zeek/files/5586190/changes-without-zeroes-removal.txt.gz)

**Comment by jsiwek** [comment] 2020-11-24 01:47
I agree 0-timestamp canonification needs some improvement since it's clearly over-sanitizing.  Simply capturing 0-timestamps in baselines is the way I'd say to try first.  If we learn later on that some test case isn't actually consistent in producing a 0-timestamp, then we may want to address those case-by-case rather than via global canonification anyway: think it's more likely to either be a real bug in need of a fix or else the test case itself needs a better structure.

**Comment by 0xxon** [comment] 2020-11-27 13:45
Perhaps I am missing something obvious - but what is the reason for us doing all the baseline updates at once?

We could just do this and slowly move over to the canonified baseline when a baseline changes, right? Which might make it less probable that we miss something.

**Comment by ckreibich** [comment] 2020-11-28 07:22
Fwiw, @0xxon ... the idea was that since these baseline updates change the baseline representation quite a bit (with the header & canonification), it's better to do a bulk update that is a no-op in terms test behavior. You could do it over time as well, but if such updates are driven by actual changes to the tests, it would be harder to see those changes.

**Comment by 0xxon** [comment] 2020-11-29 16:43
Ok, that makes sense.

**Closed** 2020-12-07 18:23 UTC
Labels: Area: CI/Testing, Type: Maintenance
