### ISSUE TITLE
HTTP Protocol Parsing Issue: Incorrect Recognition of Request and Payload Parsing

### ISSUE THREAD

**Issue by yiyisunshine** [zeek/zeek#3223] opened 2023-08-08 03:15 UTC
Issue Description:

Overview:
While using Zeek for pcap parsing, I encountered an issue with HTTP protocol analysis. The parsing incorrectly fails to identify certain GET requests, such as the example shown below. Out of the four requests present, only three are parsed correctly, and one GET request is not recognized. Initial analysis suggests that the problem arises when a GET request is combined with a POST request within the same packet. This leads to the GET request being erroneously identified as part of the payload.

Detailed Description:
I am using Zeek version 6.0.0 on Linux. I have confirmed that the network traffic packets contain both GET and POST requests. Here is a more detailed description of the problem:

`POST /cgi-bin/fpserver.cgi HTTP/1.1
Content-Type: application/octet-stream
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows 98)
Host: 204.236.23.3
Content-Length: 143
X-Session: 63604
X-Counter: 1
X-Connection: alive
X-Host: 204.236.23.3
X-Port: 80
X-Proto: tcp

GET http://182.168.2.99/rand4/lesTdhIM8uLM HTTP/1.1
User-Agent: curl/7.29.0
Host: 182.168.2.99
Accept: */*
Proxy-Connection: Keep-Alive

POST /cgi-bin/fpserver.cgi HTTP/1.1
Content-Type: application/octet-stream
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows 98)
Host: 204.236.23.3
Content-Length: 0
X-Session: 63604
X-Counter: 2
X-Connection: alive

POST /cgi-bin/fpserver.cgi HTTP/1.1
Content-Type: application/octet-stream
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows 98)
Host: 204.236.23.3
Content-Length: 0
X-Session: 63604
X-Counter: 3
X-Connection: close

`
1. During the process of traffic analysis, I observed that there are four HTTP requests. However, Zeek successfully parsed only three of them and failed to recognize one GET request.
2. Upon comparing the original content of the network packets, I identified that one GET request and one POST request are combined within the same packet.
3. Zeek seems to incorrectly interpret the GET request as a component of the packet payload, rather than parsing it as a separate HTTP request.

Expected Behavior:
I expect Zeek to accurately identify all HTTP requests, even when they are present within the same packet. The GET request should be properly parsed and displayed in the HTTP log. This would enable me to precisely monitor and analyze network traffic.

Additional Information:
I did not come across any apparent errors or warning messages within the Zeek logs. I have attempted to search the Zeek community for similar issues but haven't found a case that matches my situation.

Thank you for your assistance!

Regenerate

**Comment by 0xxon** [comment] 2023-08-08 05:46
Hi,

do you have a pcap that shows this? This will be very hard for us to diagnose without a reproducer that allows us to examine exactly what is going on.

**Comment by yiyisunshine** [comment] 2023-08-08 06:25
> Hi,
> 
> do you have a pcap that shows this? This will be very hard for us to diagnose without a reproducer that allows us to examine exactly what is going on.

[pcap](https://drive.google.com/file/d/1s5QCbPqPNrKnjTpw5a8kM9cndzHFhf7j/view?usp=sharing) thanks!

**Comment by 0xxon** [comment] 2023-08-08 09:44
Thanks for this. Looking at the pcap, it looks like Zeek is indeed parsing this correct. 

The first POST request specifies a content-length of 143 bytes. The GET request is sent as the content of the post request. Note that we are not the only ones parsing this like this - if you look at, e.g., Wireshark - it interprets this exactly the same way. The GET request is interpreted as the body of the POST.

I see that, in the stream, there seems to be indeed a reply to the GET request that was contained in the body of the POST. However, the reply to the GET request inside the post seems to be wrapped inside another HTTP response.

So what seems to be going on here is that there is a service running on the server handles wrapped HTTP requests. So what this actually is is:

HTTP post (containing HTTP GET)
HTTP reply to POST (containing second HTTP reply to the HTTP GET)
HTTP post
HTTP reply to second post

So - to sum up - this is correctly parsed; the GET is sent inside the POST data, and the reply to the GET is sent inside a wrapped HTTP reply.

**Comment by 0xxon** [comment] 2023-08-09 18:06
Closing this - please let me know if you had additional questions.

**Closed by 0xxon** 2023-08-09 18:06 UTC
