### ISSUE TITLE
High memory usage on active long kerberos SMB connections

### ISSUE THREAD

**Issue by pxscssmm** [zeek/zeek#956] opened 2020-05-06 13:45 UTC
Hello,

I would like some help with an issue we have noticed on our Zeek sensors.
A quick description of the issue is that a Zeek worker will, over time, use a large amount of memory. This issue has only appeared on a limited subset of our sensors, but the one thing they all have in common is that they monitor domain controllers/kerberos traffic.
Having done a memory dump of the affected workers, i noticed a considerable amount of SMB:: strings that usually make up around 70-80% of the bytes of the dump.
Comparing the string to what Zeek outputs in the logs, i noticed that these appear in the smb_files.log. Noticeably the logs often refer to a conn id that does not yet have a corresponding conn log entry. Upon stopping Zeek these conn log entries are created, many of the connections have duration longer than several days. 

This issue was first noticed after upgrading from Bro 2.5.5 to Bro 2.6.2, it appears to persist in Zeek 3.0.5.
The severity of the memory usage increase differs in direct correlation to the network traffic monitored. This issue appears on sensors in 2 different data centers that monitor the network ranges of the domain controllers in their data center. Other sensors in those data centers that do not monitor the same network ranges do not immediately display this issue. Stopping the affected Zeek worker frees up the memory, but then a new worker start having the same issue.
As part of a test, a sensor was given the full DC domain controller traffic, that is normally load-balanced to 2 sensors. The memory usage increased at double the rate it did when load-balanced.

**Comment by JustinAzoff** [comment] 2020-05-06 17:08
Can you see if this package fixes your  memory issues?   https://github.com/corelight/zeek-smb-clear-state

There are some corner cases in smb3 that cause issues, but so far I have been unable to get a pcap suitable for adding to the test suite to get it fixed properly.

**Comment by pxscssmm** [comment] 2020-05-08 08:41
The package appears to have indeed fixed the issue, I tested it for 24 hours on both DC's and there was no significant increase of memory usage on any of the workers as seen previously. During this time frame approximately 2634 notice log entries occurred with SMBClearState.

In this case it appears to be a significant volume of smb2 requests on certain connections that cause the notice to trigger. I have a pcap of this, but unfortunately i cannot share it publicly due to the sensitive nature of the traffic being user traffic on a data center.

**Comment by JustinAzoff** [comment] 2020-05-08 19:33
> The package appears to have indeed fixed the issue

great :-)

> In this case it appears to be a significant volume of smb2 requests on certain connections

yeah, as i understand it anything that has an error  and increments the channel sequence number, which in older dialects was the error status.

> I have a pcap of this, but unfortunately i cannot share it publicly due to the sensitive nature of the traffic being user traffic on a data center.

That's why getting this fixed properly has been so hard :-(

**Comment by rsmmr** [comment] 2020-08-13 10:21
@JustinAzoff is this something to merge back upstream (even without test pcap)?

**Comment by JustinAzoff** [comment] 2020-09-06 00:04
@jsiwek had a potential patch somewhere.. can't seem to find it now.  I believe values > 2^16 should be treated as errors and other values, especially ones that are < 256 are likely just channel sequence numbers.

**Comment by jsiwek** [comment] 2020-09-08 18:05
Was it the following patch ?

```diff
diff --git a/src/analyzer/protocol/smb/smb2-protocol.pac b/src/analyzer/protocol/smb/smb2-protocol.pac
index 6424e86d5..750ad1ea1 100644
--- a/src/analyzer/protocol/smb/smb2-protocol.pac
+++ b/src/analyzer/protocol/smb/smb2-protocol.pac
@@ -31,15 +31,17 @@ enum smb2_share_types {
 
 type SMB2_PDU(is_orig: bool) = record {
 	header     : SMB2_Header(is_orig);
-	message    : case header.status of {
+	message    : case is_msg of {
 		# Status 0 indicates success.  In the case of a
 		# request this should just happen to work out due to
 		# how the fields are set.
-		0                               -> msg                      : SMB2_Message(header, is_orig);
-		STATUS_BUFFER_OVERFLOW          -> buffer_overflow          : SMB2_Message(header, is_orig);
-		STATUS_MORE_PROCESSING_REQUIRED -> more_processing_required : SMB2_Message(header, is_orig);
-		default                         -> err                      : SMB2_error_response(header);
+		true                            -> msg                      : SMB2_Message(header, is_orig);
+		false                           -> err                      : SMB2_error_response(header);
 	};
+} &let {
+	is_msg: bool = (header.status <= 0x7fff ||
+	                header.status == STATUS_BUFFER_OVERFLOW ||
+	                header.status == STATUS_MORE_PROCESSING_REQUIRED);
 };
 
 type SMB2_Message(header: SMB2_Header, is_orig: bool) = case is_orig of {
```

That's from a year ago and I've not really dug into the problem, but that patch was just a literal translation-to-binpac of an idea Justin wanted to test, so not sure if it still matches current-day knowledge.

**Comment by petiepooo** [comment] 2020-10-02 12:35
FWIW, I'm seeing this on 3.0.10 as well.  Worker processes that are normally 0.6G RSS max were up to over 5G and triggering OOM-killer on my poor elasticsearch process.
I am also unable to provide a pcap due to sensitive contents on this production system.
Verifying now that https://github.com/corelight/zeek-smb-clear-state resolves.

**Comment by rsmmr** [comment] 2020-11-03 13:59
@petiepooo could you try that patch?

**Comment by petiepooo** [comment] 2020-11-04 21:51
@rsmmr I do have zeek-smb-clear-state loaded but was still seeing the issue.  I also found the zeek-ssl-clear-state repository, so am loading that on startup as well.  Between the two of them, things seem better, but I still have a zeek process's RSS creeping up.  Running for a couple days now, it's up to 1.8GB and appears to be steadily growing..
I did not recompile and run zeek after applying the patch above; is that what you're asking of me?  I'm only seeing this on a production system that's already overloaded, so I'd have to defer until after an upgrade or find it somewhere else.

**Comment by rsmmr** [comment] 2020-11-05 08:00
Yeah, I was hoping you could recompile with that patch. But I understand if you don't want to experiment with a production system.

Are you positive it's still SMB that's causing the memory issue, or could it be something else now that  `zeek-smb-clear-state` is loaded?

**Comment by petiepooo** [comment] 2020-11-05 12:29
I'm not sure; I suppose I assumed being I'm only seeing this on one out of about 15 systems.  How would I tell?

**Comment by jdz** [comment] 2020-11-16 12:41
FWIW I'm also experiencing this issue.  `zeek-smb-clear-state` script helps reduce memory leakage, but something still leaks.

I applied the `smb2-protocol.pac` patch from above, but the situation does not seem to have improved:

```
SMBClearState::BrokenConnection Broken smb2 connection detected. pending_cmds=1154, fid_map=607
SMBClearState::BrokenConnection Broken smb2 connection detected. pending_cmds=392, fid_map=227
SMBClearState::BrokenConnection Broken smb2 connection detected. pending_cmds=1175, fid_map=635
SMBClearState::BrokenConnection Broken smb2 connection detected. pending_cmds=809, fid_map=423
SMBClearState::BrokenConnection Broken smb2 connection detected. pending_cmds=534, fid_map=104
SMBClearState::BrokenConnection Broken smb2 connection detected. pending_cmds=691, fid_map=333
SMBClearState::BrokenConnection Broken smb2 connection detected. pending_cmds=395, fid_map=200
SMBClearState::BrokenConnection Broken smb2 connection detected. pending_cmds=1835, fid_map=927
SMBClearState::BrokenConnection Broken smb2 connection detected. pending_cmds=2841, fid_map=468
SMBClearState::BrokenConnection Broken smb2 connection detected. pending_cmds=2841, fid_map=566
SMBClearState::BrokenConnection Broken smb2 connection detected. pending_cmds=518, fid_map=112
SMBClearState::BrokenConnection Broken smb2 connection detected. pending_cmds=559, fid_map=108
SMBClearState::BrokenConnection Broken smb2 connection detected. pending_cmds=3609, fid_map=649
```

**Comment by JustinAzoff** [comment] 2020-11-18 18:44
```

event zeek_init()
{
    Analyzer::disable_analyzer(Analyzer::ANALYZER_SMB);
}
```

would completely disable smb.

The zeekctl plugin and scripts I have at https://github.com/JustinAzoff/zeek-jemalloc-profiling could help narrow down where the memory allocations you are seeing are coming from.

**Comment by jsiwek** [comment] 2020-12-08 00:15
Looking for confirmation: does the patch, https://github.com/zeek/zeek/commit/0b8535b879f1028d556b415ddccded27762e47c2, from #1311 resolve this issue?

**Comment by petiepooo** [comment] 2020-12-08 01:57
It may be a few days, but I'm hoping to have some time soon to test that on the system I have that's experiencing this.  Thanks for your work on it.

**Comment by jdz** [comment] 2020-12-10 12:27
I've been running Zeek 3.2.2 with `Analyzer::ANALYZER_SMB` disabled, and the memory is still leaking, although slower.

@jsiwek The situation seems to be the same with `3.3.0-dev.630`.

My guess is that connections are leaking, and heavy SMB traffic just makes the situation worse by attaching more data to connections.

I've also compiled Zeek with jemalloc, but to profile jemalloc itself must be recompiled with profiling enabled, and this is a bit troublesome.  I guess I'll need to build my own .deb...

**Comment by jdz** [comment] 2020-12-11 15:21
I built `libjemalloc` with profiling support.  Then it turned out profiling output was full of addresses instead of symbol names, so I guessed Zeek must be compiled in debug mode.  So I did that.  And now `zeek` crashes on startup with the following (all processes, manager, workers, logger):

```
zeek: /root/zeek/src/Dict.cc:885: void* zeek::Dictionary::Remove(const void*, int, zeek::detail::hash_t, bool): Assertion `num_iterators == 0 || (cookies && cookies->size() == num_iterators)' failed.
/opt/zeek/share/zeekctl/scripts/run-zeek: line 110: 60902 Aborted                 (core dumped) nohup ${pin_command} $pin_cpu "$myzeek" "$@"
```

Should I create an issue for this?

**Comment by jsiwek** [comment] 2020-12-11 19:56
@jdz I made #1328.  Currently, can only say that it looks like you have a script (either a custom one or one shipped with Zeek) that is removing a table/set element within a `for` loop (and that's undefined/unsupported).  Quickest way to find where may be if you have the core or process in a debugger, go up to first `Expr` frame and print its `location`.  Example:

```
frame #7: 0x000000010023e48c zeek`zeek::detail::IndexExpr::Delete(this=0x0000000111270360, f=0x00000001198313a0) at Expr.cc:2640:20
   2637		if ( ! v2 )
   2638			return;
   2639	
-> 2640		v1->AsTableVal()->Remove(*v2);
   2641		}
   2642	
   2643	ExprPtr IndexExpr::MakeLvalue()
(lldb) p *location
(zeek::detail::Location) $1 = (filename = "././test.zeek", first_line = 10, last_line = 10, first_column = 0, last_column = 0)
```

**Comment by jdz** [comment] 2020-12-16 11:25
@jsiwek I compiled Zeek with your changes from #1328, and indeed found a place where log streams are being closed while iterating over a set, approximately like this:

```
for (el in Log::active_streams)
        if (el !in kept_logs)
                Log::disable_stream(el);
```

The problem here is that it is not immediately obvious that the set that is being iterated over is being modified in a bad way.

After rewriting the code memory consumption has drastically improved, to the point that it seems the problem I've been experiencing might have been fixed (need more time to confirm).

Coincidentally previously when starting Zeek with `zeekctl` it would sometimes start with lots of messages going into `weird.log`, and restarting had a 50/50 chance of fixing the problem.  This problem seems to be gone as well.

Which brings me to the core of the problem: if this "improper" cellection modification is vital to Zeek's proper operation, why are the checks only done in `debug` mode?  It seems to me at least warnings should be issued in `release` mode.

**Comment by jsiwek** [comment] 2020-12-16 18:38
> Which brings me to the core of the problem: if this "improper" cellection modification is vital to Zeek's proper operation, why are the checks only done in `debug` mode? It seems to me at least warnings should be issued in `release` mode.

@jdz yes, I agree, and that's also addressed by the changes in #1331: the behavior no longer varies with build-type and warnings about possible loop/iteration invalidations are always given.

**Comment by rsmmr** [comment] 2021-03-09 07:29
#1331 has landed, is there anything else to do here?

**Comment by rsmmr** [comment] 2021-03-10 07:45
@pxscssmm @petiepooo @jdz How is this looking now, still seeing the issue?

**Comment by jdz** [comment] 2021-03-10 08:40
@rsmmr I'm sorry I cannot add any information to this thread because I've disabled the SMB analyzer.

**Comment by petiepooo** [comment] 2021-03-11 20:20
The traffic that I analyze has changed such that I've eliminated most SMB parsing and cannot reproduce the issue.

**Comment by pxscssmm** [comment] 2021-03-12 07:39
We are still on Zeek 3.0.X in which the issue is still present without the package. Once there has been time to test 4.0.X in our setup i will provide feedback.

**Comment by pxscssmm** [comment] 2021-05-31 07:47
Sorry for the long delay in feedback, here is what i have seen so far with version 4.0.0:
Memory usage in kerberos heavy traffic can cause affected workers to use a lot of memory (>25 GB), but this memory seems to get cleaned up nicely and usually on the weekends the kerberos affected workers go below 5 GB memory usage.
This was tested for 30 days on 5 different sensors with kerberos heavy traffic and compared to 10 different sensors with non-kerberos traffic, behaviour seemed consistent across datacenters.

It seems like the issue is solved, it is still note worthy that the zeek sensors that ingest kerberos heavy traffic still use more memory than their non-kerberos counter parts, but I think this can be closed unless someone else still sees the same issue.

**Comment by rsmmr** [comment] 2021-06-01 07:06
Thanks for confirming, I'll go ahead and close this then.

**Closed by rsmmr** 2021-06-01 07:06 UTC
Labels: Area: Protocol Analysis, Type: Bug :bug:
