### ISSUE TITLE
Segmentation Fault in hilti::rt::stream::detail::Chunk Destructor

### ISSUE THREAD

**Issue by maofeichen** [zeek/zeek#3548] opened 2024-01-11 08:37 UTC
Hello,

I am reaching out to report a specific issue we've encountered while using Zeek in conjunction with the Spicy plugin. During live network analysis, we encountered a segmentation fault in Zeek which seems related to the Spicy plugin. The crash occurs in the destructor of `hilti::rt::stream::detail::Chunk`.

**Description of the environment**
We utilize PF_RING in conjunction with Zeek for real-time network traffic analysis. In our setup, we have developed and integrated additional protocol analyzers into Zeek, leveraging the Spicy framework. However, we've encountered an issue where, after running continuously for several hours (approximately 10 hours or more), some Zeek processes start to crash due to segmentation faults. We have captured the core dumps for these crashes. And all coredumps are due to this `hilti::rt::stream::detail::Chunk`. 

**The GDB trace is as attach fig**

<img width="1219" alt="Screenshot 2024-01-11 at 4 29 07 PM" src="https://github.com/zeek/zeek/assets/1087961/75fdddbc-a65f-4c4e-bc8e-4649ca9562aa">

and the seg fault occurred at:

`hilti::rt::stream::detail::Chunk::~Chunk (this=0x55940afecdc0, __in_chrg=<optimized out>) at /root/Downloads/zeek-5.2.0/auxil/spicy/spicy/hilti/runtime/include/hilti/rt/types/stream.h:121`

**Environment**

- Zeek Version: 5.2.0
- Spicy Plugin Version: spicyc 1.7.0
- Operating System: Ubuntu 22.04 LTS

Thank you very much for your time and attention. Please feel free to reach out if additional information is required. Looking forward to any guidance or suggestions you might have.

**Comment by bbannier** [comment] 2024-01-11 08:51
Thanks a lot for your report. This looks a lot like a duplicate of zeek/spicy#1550 which was fixed with `spicy-1.9.0` (part of `zeek-6.1.0`). Could you check whether the issue is fixed with that version? I am closing this for now.

**Closed by bbannier** 2024-01-11 08:51 UTC
