### ISSUE TITLE
Composability issues with disable_analyzer()

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#1593] opened 2021-06-10 23:19 UTC
Background: the `disable_analyzer()` BiF allows a script to turn off a particular analyzer associated with a given connection identifier. This is useful for situations like when a script sets `SSL::disable_analyzer_after_detection` to `F` so it can process further into an SSL connection, and then does enough of that to determine it has no more work and wants to skip the load of processing the rest of the connection.

Problem: if two separate scripts both want this functionality, they don't compose well together.  Each will set `SSL::disable_analyzer_after_detection=F`, but then when the first one calls `disable_analyzer()` it will deactivate the analyzer even though the second still wants to continue processing.

Possible fix: add an API for scripts registering interest in a particular analyzer continuing, and disinterest once they're done.  So the above sequence might instead look like: `SSL::register_for_analysis_after_detection()` (a new function that internally just bumps a counter of how many interested parties their are, and sets `SSL::disable_analyzer_after_detection=F`), and then, for a given connection, something like `SSL::release_analysis_interest()` (which internally decrements the current usage counter, and calls `disable_analyzer()` if it has gone to zero).

It may be that this problem exists for other offloading scenarios, too.

**Comment by rsmmr** [comment] 2021-06-11 08:57
Yeah, I see how this would be useful for SSL. Not sure it generalizes beyond that as the `disable_analyzer_after_detection` is pretty specific to SSL. So sounds like something to just build into the SSL scripts.

**Comment by awelzel** [comment] 2022-08-05 13:54
Seems #1593 is a duplicate of this. Should we combine them somehow?

**Closed** 2022-08-11 14:09 UTC
Labels: Type: Enhancement, Area: Scripting
