### ISSUE TITLE
kevent broke compatibility with PF_RING ZC

### ISSUE THREAD

**Issue by cardigliano** [zeek/zeek#1063] opened 2020-07-14 15:58 UTC
It seems that *select* has been replaced by *kevent* for polling from devices in the Manager.
This broke the ability to poll from selectable file descriptors which are backed by *eventfd*. 
This is the case of SPSC queues in PF_RING ZC for instance.
This is the error you get when trying to capture from a device using an eventfd:

`error: Failed to register fd 22 from PktSrc: Bad address`
`fatal error: Failed to register pktsrc fd with iosource_mgr`

Any chance this "Bad address" error can be handles falling back to select or similar?
Thank you.

**Comment by timwoj** [comment] 2020-07-14 16:47
It might be an issue with libkqueue, but that project has been pretty responsive to fixes we've sent them previously. Do you have a plugin that implements pf_ring zc I can test against?

**Comment by cardigliano** [comment] 2020-07-14 16:53
I use it through libpcap, please see the instructions at https://www.ntop.org/guides/pf_ring/thirdparty/bro.html

**Comment by timwoj** [comment] 2020-07-15 17:45
Can you run the following and give me the output from it? This should dump a bit more debugging information from likbqueue.

```
git clone --recursive https://github.com/zeek/zeek
cd zeek
( cd auxil/libkqueue/ && sed -i 's/RelWithDebInfo/Debug/g' CMakeLists.txt && mkdir build && cd build && cmake3 -DCMAKE_INSTALL_PREFIX=./root -DSTATIC_KQUEUE=yes .. && make install && mv root/lib/libkqueued.a root/lib/libkqueue.a )
./configure --with-libkqueue=$(pwd)/auxil/libkqueue/build/root
cd build
make -j $(nproc)
. zeek-path-dev.sh 
KQUEUE_DEBUG=1 zeek -C -i eth0
```

**Comment by cardigliano** [comment] 2020-07-16 15:59
I get this configure error

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBKQUEUE_INCLUDE_DIRS (ADVANCED)
LIBKQUEUE_LIBRARIES (ADVANCED)

**Comment by timwoj** [comment] 2020-07-22 23:32
Sorry, this one fell off my todo list on Monday somehow. Let me dig into it and I'll get back to you.

**Comment by timwoj** [comment] 2020-07-23 17:18
I found a device here at my house that has an e1000e device in it and got pf_ring-zc installed on it. Zeek seems to be functioning correctly for me here with the command `zeek -C -i zc:eno1`, built against pf_ring's libpcap. I'm getting a conn.log with valid data in it, and KQUEUE_DEBUG doesn't show anything unusual. Does it work correctly for you outside of a cluster environment?

**Comment by cardigliano** [comment] 2020-07-31 08:24
eventfds are actually used for SPSC queues. PF_RING includes a load balancer (zbalance_ipc) reading from interfaces and distributing the load across multiple ZC queues. In that case eventfd is used to notify new packets.

**Comment by timwoj** [comment] 2020-08-18 19:32
Ok thanks, that was what I was missing. I'm able to reproduce it here now so let me dig into it.

**Comment by timwoj** [comment] 2020-09-04 17:37
From the above linked issue (thanks @tsqrd):

> I'm aware of the changes made in 3.1 and discussed in this blog post. Since this change I have been unable to update zeek because we rely on pf_ring ZC and zbalance_ipc (load balancing). I have compiled zeek with libpcap that has zc support.
> 
> I realize this is likely a problem with zbalance_ipc, but I'm looking for help with how to fix it so that it works with zeek > 3.1.
> 
> Version info:
> CentOS Linux release 7.7.1908
> zeek 3.3.0-dev.241
> pfring-7.7.0-3160.x86_64
> ixgbe-zc 5.5.3.3160-dkms
> 
> ```
> [root@server~]# zcount_ipc -c 10 -i 0
> =========================
> Absolute Stats: 65'273 pkts (0 drops) - 48'611'446 bytes
> Actual Stats: 43'181.73 pps (0.00 drops) - 0.24 Gbps
> =========================
> 
> [root@server~]# zeek -i zc:10@0
> listening on zc:10@0
> 
> error: Failed to register fd 22 from PktSrc: Bad address
> fatal error: Failed to register pktsrc fd with iosource_mgr
> ```
> 
> Using just pf_ring ZC without zbalance_ipc works, which leads me to believe the issue lies within zbalance_ipc
> 
> ```
> [root@server~]# zcount -i zc:eth1
> =========================
> Absolute Stats: 3'353'880 pkts (0 drops) - 2'489'825'502 bytes
> Actual Stats: 1'678'156.94 pps (0.00 drops) - 9.94 Gbps
> =========================
> 
> [root@server~]# zeek -i zc:eth1
> listening on zc:eth1
> 
> 1599228100.924088 1331766 packets received on interface zc:eth1, 5053850 (79.14%) dropped
> 
> ```

**Comment by jhaprins** [comment] 2020-10-12 22:58
I found this error report while I was in the process of upgrading my Bro cluster to a Zeek cluster. What is the latest version of Zeek that does work?

**Comment by timwoj** [comment] 2020-10-12 23:35
3.0.x should be fine. 3.1 was where we merged the changes for kqueue. I just pinged the issue on the libkqueue side to see if we can track it down before 4.0 comes out.

**Comment by timwoj** [comment] 2020-10-13 13:49
I'm happy to report that this was fixed in the library last night. I'll get a fixed version of the library into Zeek today.

**Comment by tsqrd** [comment] 2020-10-13 15:36
That is fantastic news, thanks @timwoj !

**Comment by timwoj** [comment] 2020-10-13 17:47
@cardigliano @jhaprins @tsqrd do you want to try out that commit above and see if it fixes the issue for you? I was able to test here with an e1000e device, and it was working correctly with the latest fixes from upstream.

**Closed** 2020-10-13 20:49 UTC
Labels: Area: Packet Capture, Type: Bug :bug:, Type: Maintenance

**Comment by tsqrd** [comment] 2020-10-13 22:11
@timwoj I can confirm that the latest fixes the issue.  zeek is recognizing the interfaces created by zabalance_ipc.  Thanks again, we can finally upgrade ;)

**Comment by timwoj** [comment] 2020-10-13 22:12
Glad to hear it. Thanks for giving it a spin. It's merged into master now.
