### ISSUE TITLE
HTTP header Content-Length not equal to body-length

### ISSUE THREAD

**Issue by jgvt** [zeek/zeek#1951] opened 2022-02-01 13:19 UTC
Hello,

I try to compare "Content-Length" from HTTP header to body-length but sometimes they are not equal.
I identify a connection from PCAP to focus on this issue.
https://www.unb.ca/cic/datasets/ids-2017.html
It is the Monday-workingHours.pcap, tcp stream 91 for exemple.

I tried with Wireshark and it deal with it with no difference (I extracted the HTTP object).

This is the code I use to compare these values:

event http_all_headers(c: connection, is_orig: bool, hlist: mime_header_list)
{
	for ( idx in hlist)
	{
		if ( hlist[idx]$name == "CONTENT-LENGTH" )
		{
			print "content-length";
			print hlist[idx]$value;
		}
	}
}

event http_message_done(c: connection, is_orig: bool, stat: http_message_stat)
{
	print "body_length";
	print stat$body_length;
}

<img width="950" alt="content-length" src="https://user-images.githubusercontent.com/71871506/151974105-4ad79f04-b895-4fad-b5cc-60df19b9935f.PNG">

Does anyone know why ?

**Comment by 0xxon** [comment] 2022-02-01 15:20
Could you perhaps add a minimal pcap for reproduction (so just extract the affected flow)? The download server for that dataset is abysmally slow.

**Comment by jgvt** [comment] 2022-02-01 16:07
[Monday-WorkingHours_ext.zip](https://github.com/zeek/zeek/files/7979935/Monday-WorkingHours_ext.zip)

**Comment by 0xxon** [comment] 2022-02-01 16:47
That trace seems to have some issues with packet reordering, or similar. Zeek generally does not like that very much - it expects a well-formatted TCP flow, and will discard data when there are errors in the TCP transmission. You can see this in conn.log - when missed_bytes is different than 0, there generally is a problem with the connection.

This difference is probably caused by these missed bytes.

I am not quite sure how Wireshark handles these situations - but I think it is more happy to just paste a TCP conversation together, even if the packets are invalid in the order in which they are in the trace-file.

**Comment by jgvt** [comment] 2022-02-02 09:01
Thank for your answer. Do you think that a fix will be published one day ? Is that something you want or could work on in the future? It’d be great if Zeek was more robust on that.

**Comment by 0xxon** [comment] 2022-02-02 09:59
I might have been a bit unclear on this - but this probably is purely a problem in the trace, since it looks like the data is not completely ordered in a way that makes sense for TCP. Thus, that is not really a Zeek problem - it is more of a problem that the data does not make sense, if you run a full TCP state machine.

I don't see that we will change our approach on this in the near-term future (or at all).

**Comment by timwoj** [comment] 2023-04-20 19:04
I'm closing this since it doesn't look like there's anything to do.

**Closed by timwoj** 2023-04-20 19:04 UTC
Labels: Area: Protocol Analysis
