### ISSUE TITLE
Compile time error (C1083) when building for Windows: Missing headers pcap-int, varattrs, fmtutils, etc.

### ISSUE THREAD

**Issue by d4rk-d4nph3** [zeek/zeek#2896] opened 2023-03-25 18:33 UTC
## My dev setup

Zeek v5.2's conanfile_windows.txt uses generators (_cmake_ and _cmake_find_package_) that are deprecated from conan v2 onwards. So, as a workaround, I used an older version (1.53.0) to proceed.

## Error

```sh
cmake.exe --build .
[0/190] Building libkqueue
ninja: no work to do.
[3/190] Building CXX object src\iosource\CMakeFiles\bro_iosource.dir\BPF_Program.cc.obj
FAILED: src/iosource/CMakeFiles/bro_iosource.dir/BPF_Program.cc.obj
C:\PROGRA~2\MICROS~2\2019\BUILDT~1\VC\Tools\MSVC\1429~1.301\bin\Hostx86\x64\cl.exe  /nologo /TP -DCARES_STATICLIB -DDOCTEST_CONFIG_NO_MULTITHREADING -DDOCTEST_CONFIG_SUPER_FAST_ASSERTS -Isrc\iosource -I..\src\iosource -Isrc\include -Isrc -I..\src\include -I..\src -I. -I..\auxil\out_ptr\include -Ilibkqueue-build\include -I..\auxil\libkqueue\include -I..\auxil\rapidjson\include -I..\auxil\paraglob\include -I..\auxil\highwayhash -Iauxil\broker\include -I..\auxil\broker\include -I"C:\Program Files\OpenSSL-Win64\include" -IC:\Users\administrator1\.conan\data\zlib\1.2.11\_\_\package\3fb49604f9c2f729b85ba3115852006824e72cab\include -Iauxil\binpac\lib -I..\auxil\binpac\lib -IC:\Users\administrator1\.conan\data\libpcap\1.10.1\_\_\package\3fb49604f9c2f729b85ba3115852006824e72cab\include -I..\auxil\libunistd\regex -I..\auxil\libunistd\unistd -IC:\Users\administrator1\.conan\data\c-ares\1.18.1\_\_\package\95ac61b4b7e9e66bcc9af3260647ab977ee3250a\include /DWIN32 /D_WINDOWS /GR /EHsc /std:c++17 /O2 /Ob2 /DNDEBUG /MT -MT /guard:cf /Z7 /showIncludes /Fosrc\iosource\CMakeFiles\bro_iosource.dir\BPF_Program.cc.obj /Fdsrc\iosource\CMakeFiles\bro_iosource.dir\ /FS -c ..\src\iosource\BPF_Program.cc
..\src\iosource\BPF_Program.cc(19): fatal error C1083: Cannot open include file: 'pcap-int.h': No such file or directory
ninja: build stopped: subcommand failed.
```

## But the dependencies are satisfied

```sh
C:\Users\administrator1\Desktop\zeek-5.2.0\build>cmake.exe .. -DCMAKE_BUILD_TYPE=release -DENABLE_ZEEK_UNIT_TESTS=yes -G Ninja
-- Conan: Detected VS runtime: MT
-- Conan: checking conan executable
-- Conan: Found program C:/Program Files/Conan/conan/conan.exe
-- Conan: Version found Conan version 1.53.0
-- Conan executing: C:/Program Files/Conan/conan/conan.exe install C:/Users/administrator1/Desktop/zeek-5.2.0/ci/windows/conanfile_windows.txt --build missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

c-ares/1.18.1: Main binary package '0d8f5db5c856dac708638c4f0c05c3fb5b166905' missing. Using compatible package '95ac61b4b7e9e66bcc9af3260647ab977ee3250a'
libpcap/1.10.1: Main binary package 'aeb780fff478e1cdc4810c56d2e5033ddca73550' missing. Using compatible package '3fb49604f9c2f729b85ba3115852006824e72cab'
zlib/1.2.11: Main binary package 'aeb780fff478e1cdc4810c56d2e5033ddca73550' missing. Using compatible package '3fb49604f9c2f729b85ba3115852006824e72cab'
conanfile_windows.txt: Installing package
Requirements
    c-ares/1.18.1 from 'conancenter' - Cache
    libpcap/1.10.1 from 'conancenter' - Cache
    zlib/1.2.11 from 'conancenter' - Cache
Packages
    c-ares/1.18.1:95ac61b4b7e9e66bcc9af3260647ab977ee3250a - Cache
    libpcap/1.10.1:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    zlib/1.2.11:3fb49604f9c2f729b85ba3115852006824e72cab - Cache

Installing (downloading, building) binaries...
c-ares/1.18.1: Already installed!
libpcap/1.10.1: Already installed!
zlib/1.2.11: Already installed!
conanfile_windows.txt: Generator txt created conanbuildinfo.txt
conanfile_windows.txt: Generator cmake created conanbuildinfo.cmake
conanfile_windows.txt: Generator cmake_find_package created FindZLIB.cmake
conanfile_windows.txt: Generator cmake_find_package created Findlibpcap.cmake
conanfile_windows.txt: Generator cmake_find_package created Findc-ares.cmake
conanfile_windows.txt: Aggregating env generators
conanfile_windows.txt: Generated conaninfo.txt
conanfile_windows.txt: Generated graphinfo
-- Conan: Using autogenerated Findlibpcap.cmake
-- Found libpcap: 1.10.1 (found version "1.10.1")
-- Library pcap_static found C:/Users/administrator1/.conan/data/libpcap/1.10.1/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab/lib/pcap_static.lib
```

## Files in my iosource\pcap directory

```sh
dir C:\Users\administrator1\Desktop\zeek-5.2.0\build\src\iosource\pcap
 Volume in drive C is Windows
 Volume Serial Number is CA64-C4C6

 Directory of C:\Users\administrator1\Desktop\zeek-5.2.0\build\src\iosource\pcap

03/25/2023  02:27 PM    <DIR>          .
03/25/2023  02:27 PM    <DIR>          ..
03/25/2023  01:36 PM    <DIR>          CMakeFiles
03/25/2023  01:36 PM             1,069 cmake_install.cmake
03/25/2023  01:36 PM               345 CTestTestfile.cmake
03/25/2023  02:06 PM             2,873 pcap-stdinc.h
03/25/2023  01:45 PM             8,380 pcap.bif.cc
03/25/2023  01:45 PM             1,693 pcap.bif.h
03/25/2023  01:45 PM             1,331 pcap.bif.init.cc
```

## My naive workaround attempt

In steps, I placed the missing header files from [_libpcap_](https://github.com/the-tcpdump-group/libpcap) to the _iosource_ directory. In total, I placed _pcap-int.h, varattrs.h, fmtutils.h_ and _portability.h_. However, when I placed _portability.h,_ the compiler gave me a new error.

```sh
cmake.exe --build .
[0/190] Building libkqueue
ninja: no work to do.
[3/190] Building CXX object src\iosource\CMakeFiles\bro_iosource.dir\BPF_Program.cc.obj
FAILED: src/iosource/CMakeFiles/bro_iosource.dir/BPF_Program.cc.obj
C:\PROGRA~2\MICROS~2\2019\BUILDT~1\VC\Tools\MSVC\1429~1.301\bin\Hostx86\x64\cl.exe  /nologo /TP -DCARES_STATICLIB -DDOCTEST_CONFIG_NO_MULTITHREADING -DDOCTEST_CONFIG_SUPER_FAST_ASSERTS -Isrc\iosource -I..\src\iosource -Isrc\include -Isrc -I..\src\include -I..\src -I. -I..\auxil\out_ptr\include -Ilibkqueue-build\include -I..\auxil\libkqueue\include -I..\auxil\rapidjson\include -I..\auxil\paraglob\include -I..\auxil\highwayhash -Iauxil\broker\include -I..\auxil\broker\include -I"C:\Program Files\OpenSSL-Win64\include" -IC:\Users\administrator1\.conan\data\zlib\1.2.11\_\_\package\3fb49604f9c2f729b85ba3115852006824e72cab\include -Iauxil\binpac\lib -I..\auxil\binpac\lib -IC:\Users\administrator1\.conan\data\libpcap\1.10.1\_\_\package\3fb49604f9c2f729b85ba3115852006824e72cab\include -I..\auxil\libunistd\regex -I..\auxil\libunistd\unistd -IC:\Users\administrator1\.conan\data\c-ares\1.18.1\_\_\package\95ac61b4b7e9e66bcc9af3260647ab977ee3250a\include /DWIN32 /D_WINDOWS /GR /EHsc /std:c++17 /O2 /Ob2 /DNDEBUG /MT -MT /guard:cf /Z7 /showIncludes /Fosrc\iosource\CMakeFiles\bro_iosource.dir\BPF_Program.cc.obj /Fdsrc\iosource\CMakeFiles\bro_iosource.dir\ /FS -c ..\src\iosource\BPF_Program.cc
..\src\iosource\BPF_Program.cc(21): error C2733: 'pcap_freecode': you cannot overload a function with 'extern "C"' linkage
C:\Users\administrator1\.conan\data\libpcap\1.10.1\_\_\package\3fb49604f9c2f729b85ba3115852006824e72cab\include\pcap/pcap.h(622): note: see declaration of 'pcap_freecode'
..\src\iosource\BPF_Program.cc(44): error C2039: 'fd': is not a member of 'pcap'
C:\Users\administrator1\Desktop\zeek-5.2.0\build\src\iosource\pcap-int.h(223): note: see declaration of 'pcap'
..\src\iosource\BPF_Program.cc(51): error C2733: 'pcap_compile_nopcap': you cannot overload a function with 'extern "C"' linkage
C:\Users\administrator1\.conan\data\libpcap\1.10.1\_\_\package\3fb49604f9c2f729b85ba3115852006824e72cab\include\pcap/pcap.h(617): note: see declaration of 'pcap_compile_nopcap'
..\src\iosource\BPF_Program.cc(146): error C2660: 'pcap_freecode': function does not take 2 arguments
C:\Users\administrator1\.conan\data\libpcap\1.10.1\_\_\package\3fb49604f9c2f729b85ba3115852006824e72cab\include\pcap/pcap.h(622): note: see declaration of 'pcap_freecode'
ninja: build stopped: subcommand failed.
```

### Please advise how to proceed.

**Comment by timwoj** [comment] 2023-03-27 17:08
> Zeek v5.2's conanfile_windows.txt uses generators (cmake and cmake_find_package) that are deprecated from conan v2 onwards. So, as a workaround, I used an older version (1.53.0) to proceed.

Yeah, unfortunately conan.cmake hasn't been updated to support Conan 2.0 yet, so we're stuck on 1.x for the time being. They have an experimental version on a branch that supports 2.0 but we'd rather wait for the official release of that. I'm using 1.54.0 on my local Windows 10 machine and our CI setup uses 1.58.0. I'll see if I can reproduce what you're seeing.

**Comment by timwoj** [comment] 2023-03-27 18:20
I cleaned out my builds and re-ran a build from VS2022, and it built fine. Here's the compile line for BPF_Program.cc:

```
  [1120/1352] C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\cl.exe  /nologo /TP -DCARES_STATICLIB -DDOCTEST_CONFIG_NO_MULTITHREADING -DDOCTEST_CONFIG_SUPER_FAST_ASSERTS -ID:\repos\zeek\out\build\x64-Debug\src\iosource -ID:\repos\zeek\src\iosource -ID:\repos\zeek\out\build\x64-Debug\src\include -ID:\repos\zeek\out\build\x64-Debug\src -ID:\repos\zeek\src\include -ID:\repos\zeek\src -ID:\repos\zeek\out\build\x64-Debug -ID:\repos\zeek\auxil\out_ptr\include -ID:\repos\zeek\out\build\x64-Debug\libkqueue-build\include -ID:\repos\zeek\auxil\libkqueue\include -ID:\repos\zeek\auxil\rapidjson\include -ID:\repos\zeek\auxil\paraglob\include -ID:\repos\zeek\auxil\highwayhash -ID:\repos\zeek\out\build\x64-Debug\auxil\broker\include -ID:\repos\zeek\auxil\broker\include -I"C:\Program Files\OpenSSL-Win64\include" -IC:\Users\timwo\.conan\data\zlib\1.2.11\_\_\package\3682397a88110bb423c0b4c7c75a818b7fdf9bd9\include -ID:\repos\zeek\out\build\x64-Debug\auxil\binpac\lib -ID:\repos\zeek\auxil\binpac\lib -IC:\Users\timwo\.conan\data\libpcap\1.10.1\_\_\package\3682397a88110bb423c0b4c7c75a818b7fdf9bd9\include -ID:\repos\zeek\auxil\libunistd\regex -ID:\repos\zeek\auxil\libunistd\unistd -IC:\Users\timwo\.conan\data\c-ares\1.18.1\_\_\package\45991e3747bc05011cd848d5d920dafa7f4a3c2e\include /DWIN32 /D_WINDOWS /GR /EHsc /std:c++17  /Ob0 /Od /RTC1 /MTd /DDEBUG -MTd /guard:cf /Z7 /showIncludes /Fosrc\iosource\CMakeFiles\bro_iosource.dir\BPF_Program.cc.obj /Fdsrc\iosource\CMakeFiles\bro_iosource.dir\ /FS -c D:\repos\zeek\src\iosource\BPF_Program.cc
```

I can nuke my .conan directory and build from the command-line too, but first I want to check one thing. If you look at `zeek-config.h` in your build directory, what do you have for the `DONT_HAVE_LIBPCAP_PCAP_FREECODE` option? Mine is marked `#undef`, as it should be on Windows. We'd only try to include `pcap-int.h` if that was defined. If it's defined on your side, we'll have to figure out why.

**Comment by d4rk-d4nph3** [comment] 2023-03-28 08:14
I rebuilt the source in a fresh Windows instance and the error didn't occur this time. Looks like in my first attempt, it might be due to my version change of conan. This time I installed conan v1.58.0 before starting the build process.

The build produced the Zeek binary however it fails to run by saying

```
fatal error: can't find base/init-bare.zeek
```
Up to my knowledge, I have correctly configured all the environment variables needed by Zeek.

```sh
ZEEKPATH=C:\Users\wadmin\Repo\zeek\build\zeek-path-dev
ZEEK_PLUGIN_PATH=C:\Users\wadmin\Repo\zeek\build\src
SPICY_PATH=C:\Users\wadmin\Repo\zeek\build\spicy-path
HILTI_CXX_INCLUDE_DIRS=C:\Users\wadmin\Repo\zeek\build\hilti-cxx-include-dirs
Path=C:\Python311\Scripts\;C:\Python311\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\bin;C:\Program Files\Git\cmd;C:\Users\wadmin\Repo\zeek\build;C:\Users\wadmin\Repo\zeek\build\src;C:\Users\wadmin\Repo\zeek\build\auxil\spicy\spicy\bin;C:\Users\wadmin\Repo\zeek\build\src\builtin-plugins\spicy-plugin\bin;C:\Program Files\Conan\conan;C:\Users\wadmin\AppData\Local\Microsoft\WindowsApps;C:\Program Files\OpenSSL-Win64\bin;
```

My Zeek path is C:\Users\wadmin\Repo\zeek.
Upon search, the init-bare.zeek is in C:\Users\wadmin\Repo\zeek\scripts\base.

Is there any post-build process I need to follow in order to successfully run the binary?

**Comment by timwoj** [comment] 2023-03-28 19:40
`ZEEKPATH` needs to point to the fully-expanded set of paths that `zeek-path-dev` would result in on Linux systems. For example, on my system it looks like:

```
.;D:\repos\zeek\scripts;D:\repos\zeek\scripts\policy;D:\repos\zeek\scripts\site;D:\repos\zeek\out\build\x64-Debug-vs2019\scripts;D:\repos\zeek\out\build\x64-Debug-vs2019\scripts\builtin-plugins
```

You can run build\zeek-path-dev.sh from a bash shell on Windows to see what it would output. We probably out to create .bat/.ps1 versions of those scripts at some point as well.

**Comment by d4rk-d4nph3** [comment] 2023-03-29 04:44
I see. Now, it is working for me too. 

I gave zeek some offline PCAPs and it works fine, however it fails to work on live-mode when pointed to my network interface by giving this error

```
fatal error: problem with interface Ethernet (pcap_error: not open (pcap_create))
```

My interface name is Ethernet.

```pwsh
PS C:\Users\wadmin> Get-NetAdapter | select name

name
----
Ethernet
```

**Comment by timwoj** [comment] 2023-03-29 17:02
You can't do live mode with the default libpcap because it doesn't support network interfaces (it's a long history of things on Windows). To do live captures, you'll need to download npcap and build against that.

This issue is straying into support questions though, which we generally don't handle via GitHub. Feel free to hit me up in the #windows channel on Slack and we can work through that part. I'm going to close this issue as it doesn't appear that we have anything to fix here.

**Closed by timwoj** 2023-03-29 17:02 UTC
