### ISSUE TITLE
Zeek completely failed to detect HTTP and FTP traffic if it came from source port 53

### ISSUE THREAD

**Issue by iyuvalk** [zeek/zeek#2282] opened 2022-07-18 15:18 UTC
A penetration tester that we worked with tried to do a brute-force attempt against our servers that their traffic is mirrored to Zeek and we noticed that if the source port is set to 53 Zeek will completely misinterpret this traffic and will only generate zeek conn events and not zeek http or zeek ftp events.

This is the command the penetration tester used:
```
nmap -n -Pn -p 21 --source-port 53 --script ftp-brute --script-args "userdb=c:\users\vagrant\user.txt,passdb=c:\users\vagrant\pass.txt" <target_server_ip> -v
```

We are using the latest Zeek version (5.0.0).
Any ideas?

**Comment by iyuvalk** [comment] 2022-07-19 13:20
Hi. 

Here are the pcap files of two FTP sessions (https://drive.google.com/drive/folders/1RVpXUTGXSvFbB20kAbY1KYJAJJ4TBOg8?usp=sharing), one from port 53 and another from normal, random port. We did detect now that Zeek is not ALWAYS failing at the detection of such sessions but in most cases it failed and created just zeek_conn events and not zeek_ftp events.

I'd love to know what is the reason for that.

Thanks,
Yuval.

**Comment by awelzel** [comment] 2022-08-15 12:51
Hello @iyuvalk - the pcaps in the google drive folder are both the same, neither using source port 53. Could you verify and re-upload a pcap with the suspected issue?

I did construct two pcaps using tcprewrite from the existing traces:
```
$ tcprewrite -i ../testing/btest/Traces/http/get.trace -o get-source-port-53.trace --portmap 59856:53
$ tcprewrite -i ../testing/btest/Traces/ftp/ipv4.trace -o ipv4-source-port-53.trace --portmap 50003:53
```
[get-source-port-53.trace.gz](https://github.com/zeek/zeek/files/9337292/get-source-port-53.trace.gz)
[ipv4-source-port-53.trace.gz](https://github.com/zeek/zeek/files/9337291/ipv4-source-port-53.trace.gz)


On first sight, the http and ftp logs are created the same as when using the original source port, so there's probably something else going on.

```
cat http.log
#separator \x09
#set_separator  ,
#empty_field    (empty)
#unset_field    -
#path   http
#open   2022-08-15-14-46-51
#fields ts      uid     id.orig_h       id.orig_p       id.resp_h       id.resp_p       trans_depth     method  host    uri     referrer        version user_agent      origin  request_body_len        response_body_len       status_code     status_msg      info_code       info_msg        tags    username        password        proxied orig_fuids orig_filenames   orig_mime_types resp_fuids      resp_filenames  resp_mime_types
#types  time    string  addr    port    addr    port    count   string  string  string  string  string  string  string  count   count   count   string  count   string  set[enum]       string  string  set[string]     vector[string]  vector[string]  vector[string]  vector[string]  vector[string]  vector[string]
1362692526.939527       CJKFoj4bpHEhTeaRoj      141.142.228.5   53      192.150.187.43  80      1       GET     bro.org /download/CHANGES.bro-aux.txt   -       1.1     Wget/1.14 (darwin12.2.0)        -       0       4705    200     OK      -       -       (empty) -       -       -       -       -       -       FDPahg4I3NTLpfSr9       -       text/plain
#close  2022-08-15-14-46-51
```

```
$ cat ftp.log
#separator \x09
#set_separator  ,
#empty_field    (empty)
#unset_field    -
#path   ftp
#open   2022-08-15-14-49-11
#fields ts      uid     id.orig_h       id.orig_p       id.resp_h       id.resp_p       user    password        command arg     mime_type       file_size       reply_code      reply_msg       data_channel.passive    data_channel.orig_h     data_channel.resp_h     data_channel.resp_p     fuid
#types  time    string  addr    port    addr    port    string  string  string  string  string  count   count   string  bool    addr    addr    port    string
1329843175.680248       CF1Qca4XkMjJWGN7oc      141.142.220.235 53      199.233.217.249 21      anonymous       test    PASV    -       -       -       227     Entering Passive Mode (199,233,217,249,221,90)  T       141.142.220.235 199.233.217.249 56666   -
1329843179.815947       CF1Qca4XkMjJWGN7oc      141.142.220.235 53      199.233.217.249 21      anonymous       test    PASV    -       -       -       227     Entering Passive Mode (199,233,217,249,221,91)  T       141.142.220.235 199.233.217.249 56667   FEDbaA44a90dKFRzf3
1329843179.926563       CF1Qca4XkMjJWGN7oc      141.142.220.235 53      199.233.217.249 21      anonymous       test    RETR    ftp://199.233.217.249/./robots.txt      text/plain      77      226     Transfer complete.      -       -       -       -       F6wZ8iqUoaPxGYCAj
1329843194.040188       CF1Qca4XkMjJWGN7oc      141.142.220.235 53      199.233.217.249 21      anonymous       test    PORT    141,142,220,235,131,46  -       -       200     PORT command successful.        F       199.233.217.249 141.142.220.235 33582   F6wZ8iqUoaPxGYCAj
1329843197.672179       CF1Qca4XkMjJWGN7oc      141.142.220.235 53      199.233.217.249 21      anonymous       test    PORT    141,142,220,235,147,203 -       -       200     PORT command successful.        F       199.233.217.249 141.142.220.235 37835   F7BoKm1QaCQXKASXLl
1329843197.727769       CF1Qca4XkMjJWGN7oc      141.142.220.235 53      199.233.217.249 21      anonymous       test    RETR    ftp://199.233.217.249/./robots.txt      text/plain      77      226     Transfer complete.      -       -       -       -       FIXQK42rXgY0sM33Ue
```

**Comment by awelzel** [comment] 2022-10-27 13:09
Hello @iyuvalk - I'm going to close this issue. Feel free to re-open if the above two comments aren't sufficient or you have a pcap reproducing the issue you initially reported.

For the nmap FTP brute-forcing experiment not producing ftp.log, the culprit seems to be that by default `FTP::logged_commands` does not include the commands used during the brute-forcing. If you add `USER` there, the ftp.log should be generated. Alternatively, the `ftp/detect-bruteforcing` script was pointed out.

**Closed by awelzel** 2022-10-27 13:09 UTC
