### ISSUE TITLE
sessions for non-analyzed protocols should still be tracked with a conn entry

### ISSUE THREAD

**Issue by ekoyle** [zeek/zeek#3915] opened 2024-09-04 18:16 UTC
Zeek's current behavior of silently ignoring traffic for which there is no analyzer is quite unexpected to new users. The assumption is that the conn log should contain data similar netflow or firewall logs.

There are many protocols where the mere presence of the protocol is a very interesting finding even if we aren't interested in protocol details. For example, is someone else's equipment trying to speak OSPF to your routers? Is there IP traffic using an uncommon or unregistered protocol number on your network? How much traffic is going over IPSEC connections on your network? Currently, zeek is not providing visibility into these behaviors in the conn log.

I would like to propose that at a minimum we create conn entries for all IP protocols with a minimum of a 3-tuple (orig_h, resp_h, and proto) and use similar logic to ICMP to determine when a connection has ended (ie. timeout). This should be enough to bring the conn log to parity with firewall logs with respect to traffic other than TCP, UDP, and ICMP.

**Comment by bbannier** [comment] 2024-09-05 07:28
FTR, there is [`unknown_protocols.log`](https://docs.zeek.org/en/master/scripts/policy/misc/unknown-protocols.zeek.html), but its entries are not tied to connections, and we also do not report information like e.g., data volume.

**Comment by timwoj** [comment] 2024-09-10 15:48
I worked on this a bit today. There's a changeset sitting on the `topic/timw/3915-unknown-ip-protocol` branch, if you want to play with it. It sets the protocol field to `unknown_transport` and encodes the IP protocol number in both port numbers in the 5-tuple. 

@j-gras: @awelzel said you might be interested in checking this out too.

**Comment by ekoyle** [comment] 2024-09-10 21:22
I'm assuming there is something in the zeek design which makes it difficult to put the IP protocol in the proto field? If so, would it be possible to at least decode the IP protocol from the port field(s) and display that in the `proto` field in logs?

I'm hoping there is a way to make the end result less "magic" than putting the protocol number in a port field since there is already a proto field that appears to contain the IP protocol (tcp, udp, icmp). You could check `/etc/protocols` or use [IANA's protocol registry](http://www.iana.org/assignments/protocol-numbers) for mappings.

**Comment by timwoj** [comment] 2024-09-11 08:09
> If so, would it be possible to at least decode the IP protocol from the port field(s) and display that in the proto field in logs?

@awelzel and I talked about that very idea yesterday. Wedecided it could be misleading if the protocol was tagged with the right name but not actually confirmed. I could see maybe tagging it with some prefixed name though, just to be clear that we didn't actually parse/confirm the protocol.

**Comment by J-Gras** [comment] 2024-09-12 07:34
Great work! One thing I am slightly concerned about is that we further blur the notion of ports in `conn.log`. I know we do the same for ICMP. However, there is only a handful of status codes. Now seeing "port 80" could also mean we are looking at ISO-IP. I think it's worth to consider a new log at this point. Another option could be to set the port to 0 and use a different column (wouldn't encode too much information into a single column though). Maybe even worth to survey users how they think about this.

**Comment by timwoj** [comment] 2024-09-12 07:44
We spent a long time talking about this as a team yesterday and this is where we landed
- Add a new field to conn.log called `proto_id` that has the numeric protocol identifier
- Leave the `port` fields set to zero for unhandled protocols
- Leave the `proto` field set to `unknown_transport`
- Add a policy file that you can load to get an additional column with the string version of the protocol

**Comment by ekoyle** [comment] 2024-09-12 19:41
I think the first question anyone will want answered if they see `unknown_transport` is: what was the IP protocol? Requiring a configuration change to add that info doesn't seem ideal, so I would advocate for including it by default.

Also, I'm not sure how much we gain by making users look in a different field simply because zeek doesn't know how to analyze the protocol. From a user standpoint, I think I'd rather see `proto` in the conn log set to the IP proto and a flag to indicate that it is unconfirmed so that the common case of zeek not handling a protocol (anything other than tcp, udp, or icmp) doesn't require special handling of the log data.

**Comment by timwoj** [comment] 2024-09-13 10:47
> From a user standpoint, I think I'd rather see `proto` in the conn log set to the IP proto and a flag to indicate that it is unconfirmed so that the common case of zeek not handling a protocol (anything other than tcp, udp, or icmp) doesn't require special handling of the log data.

From a technical perspective, that field is currently an enum underneath, even though it prints out as a string. Changing it to be a number or a string would require quite a large amount of changes to both zeek core and other plugins.

We could extend the enum to include all of the other types, but we would need a way to indicate that the protocol wasn't parsed correctly, which is kind of the point the `unknown_transport` value. We don't want the field to say `sctp` for example, when we didn't actually properly parse the SCTP protocol.

**Comment by timwoj** [comment] 2024-09-13 11:03
> I think the first question anyone will want answered if they see unknown_transport is: what was the IP protocol? Requiring a configuration change to add that info doesn't seem ideal, so I would advocate for including it by default.

I would argue that not everyone is familiar with all of the protocols as it is. If we make the field say "DSP", would you know at a glance what that is without having to go look it up? How is that any different from having to look up the protocol number itself?

We could add all of the existing protocols to the enum, but we would need some way to indicate that we didn't parse ones that we don't support. We were ok with adding a field for the protocol identifier, so maybe we just add a boolean field that indicates if the IP protocol was parsed? I'd also argue with renaming that enum from `transport_proto` to something else, since it wouldn't just be transport protocols anymore.

@rsmmr @ckreibich Thoughts?

**Comment by ckreibich** [comment] 2024-09-13 11:25
I agree with that thinking Tim. Even if we wanted to report "meaningful" strings for all protocols, we couldn't — many are not defined, but you might still see any of them on your network — so they'd have to be something like "143" or "unassigned-143" for ones not labeled in the current registry. Not great.

Also, there's a bunch of legacy awkwardness here that we don't really want to pile onto. The fact that `transport_proto` is an enum, that its naming indicates that it's about transport protocols but also covers ICMP (i.e. that lots of IP protocols aren't transports), and that it's currently symmetric with the protocol part of ports, says to me that we should not complicate this further.

If people want to know the IP protocol, the new field gives them that — for any possible value, as-is on the wire. It also gives you a natural way to distinguish what we recognize vs what we parse into — the former is a conn entry with an `unknown_transport` but a protocol number you can pull up, the latter is one with a concrete `transport_proto` value. I agree that `unknown_transport` is not great naming ("unhandled_transport" would be better, perhaps), but I think that's acceptable.

If this is a step towards deprecating (or at least shifting focus away from) `transport_proto`, I think that's a good thing.

**Comment by stevesmoot** [comment] 2024-09-13 13:51
I think I'm with Eldon here, put more info into the "obvious" place. If you want to label it the most accurately, then something like labeled_DST or labeled_253 to indicate the lack of parsing.  in logs (what most users care about), its proto, not transport_proto, so not worried about the mismatch, but could do a replace-all in the code if you want to feel better about accuracy there.

**Comment by awelzel** [comment] 2024-09-14 12:57
> It also gives you a natural way to distinguish what we recognize vs what we parse into — the former is a conn entry with an unknown_transport but a protocol number you can pull up, the latter is one with a concrete transport_proto value. 

To emphasize this one, `unknown_transport` will also imply that ports will be `0/unknown` and invalid/not-to-be-used, even for protocols that do have ports (UDP lite or SCTP). Without explicit support, Zeek will collapse any potential 5 tuple flow key into 3 in the conn.log (so 5 consecutive UDP lite connections might end up as a single conn.log entry). IMO, using `unknown_transport` in `proto` helps underline/communicate this limited support.

**Comment by timwoj** [comment] 2024-09-14 13:23
Another couple of caveats with extending the `transport_proto` enum:
- Protocol values 146-252 are considered "unassigned". Should there be entries for all of those?
- If you're using preallocated `PortVal` objects (which we use by default), those arrays go from 262k values to 16mil values. That's not an inconsequential amount of memory.

**Comment by ekoyle** [comment] 2024-09-16 20:14
To be clear, I am mainly concerned with the `proto` field in the logs. From a user standpoint, that appears to be the IP protocol of the traffic to me (and also happens to be what netflow, firewall logs, etc put in a similar field). I think we have an opportunity to adjust the definition of this field to be the obvious meaning now since we aren't tracking these connections at all currently, but we will not have that luxury in the future (or it will at least become much more difficult).

From an end-user perspective, populating the `proto` log field with the IP protocol would yield the most expected results. I think creating an ip_protocol field somewhere and using it to populate `proto` in the log would be a reasonable approach, and there may be other approaches that would work equally well.

I also don't think we should try to fiddle with the `proto` log field based on whether zeek thinks the traffic is actually what it claimed to be, as the most common case will be that there isn't a zeek analyzer for the protocol at all. If we want to surface that information in another field, that would be great, but let `proto` be the protocol declared in the packet. I would rather see whatever is presently in `proto` renamed to a new log field than making `proto` something different than the rest of the world is going to expect.

**Comment by rsmmr** [comment] 2024-09-19 08:42
I don't quite understand the issue: the proposal is to have a new column `proto_id` that has the raw on-the-wire protocol number; always there, with no further Zeek interpretation applied (we could call it `ip_proto` to make that even more clear). You can then just see the current `proto` as a legacy field if you want and ignore it.
 
Sure, we could take the liberty to just change `proto` accordingly instead, but I'd be worried about breaking lots of people's tooling by making such a change to `conn.log`. We've seen in the past how sensitive various log analyses out there are to changes to existing fields, and `conn.log` is certainly the most used log of all. Adding a new field here with the semantics we want seems much less disruptive than changing `proto`. As Christian said, we could eventually deprecate `proto` altogether, but that would need to be a slow process.

**Comment by ekoyle** [comment] 2024-09-24 05:35
As I understand the current situation, the only values in `proto` are: `icmp`, `tcp`, or `udp`; and I'm not aware of any case where there values don't match the innermost IP protocol field. If the IP header protocol field contains anything else or zeek decides the packet is not actually the protocol stated, then the connection is not tracked and therefore never logged. 

If I'm understanding the situation correctly, changing the semantics of this field would have no effect on any session that is currently being logged. It seems more straightforward to me to simply make that field mean "the IP protocol as registered with IANA" rather than something that is really just a zeek implementation detail, followed by extra work to create a new field and maybe deprecate the existing one. I think my proposed definition is what most users believe the field means today, even though it is technically something else. I think users will be just as surprised by a different value in that field as they are by the fact that other protocols aren't being logged in the conn log.

**Comment by ekoyle** [comment] 2024-09-24 13:22
Someone pointed out to me outside this discussion that there could be code that looks at the value of proto in the log value rather than the conn entry, which would be a major problem for changing the data type in the logs. That could be really difficult to resolve, especially for third-party scripts. I hadn't considered this aspect, but I see why it would be a problem now.

**Comment by initconf** [comment] 2024-09-27 15:14
I think instead of tinkering with the conn.log we should have a new log call it  `protocol.log` or `ip.log` or even better `unknown-protocols.log` - something on that lines.

This new log has all IP flows for which zeek does not know the protocol - so a report of known-unknowns. 

Here is benefits of having a separate log:

1.  Does not pollute the conn.log  - Given that unknown_protocol is unparsed at protocol-analyzer level and we don't know much about what kind of traffic it is; so a vast majority of columns in conn.log are going to be empty or plain just wrong/misleading. for example:

      a. We are already ttoying with the notion of ports (putting zero's artificially) 
      b. there is no way we can correctly fill fields like `proto` `service` `duration` `conn_state` `missed_bytes` `history` etc etc etc. 
      c. we are already bound to previous design issues such as enum  (which now seen tcp centric) 
     d.  that *ideally* adding a *new* column to conn.log should be avoided at all costs. too much can break in post analysis world for non json people. 

2. That said,  the new `unknown_protocols.log` has some advantages:
 
      a. We can pick and choose what ever columns we want in there. New log will be technically correct and reflection of actual bytes on the wire unlike force fitting things in conn.log (which is - like it or not - centered towards tcp, udp and icmp) 

    b. right now we don't see any of the `unknown_protocol` traffic anyways - so conn.log is already missing this data.  so does not affect any current analysis or scripts. ( Infact adding new columns and forcing new data in conn.log will on the other hand affect conn.log analysis and scripts ) 

     c. new log can give a better picture of known_unknowns ! it can reflect `ip header` a lot better and with more precision 
     
     d. Lets say tomorrow zeek does have analyzer for new protocols ( IGMP, GRE, DCCP) we are anyways going to have a new log file for that. Right ?

this new `unknown_protocols.log` can truly reflect the contents of IP header with a lot more precision and flexibility than squeezing all that info into conn.log resulting in a misfit/mis-understand/misinterpretations esp. for new users.

**Comment by J-Gras** [comment] 2024-10-08 15:43
I've talked to @vpax  a bit about this and he came up with a cool idea: Just support all approaches with corresponding policy scripts, i.e.
- integration into `conn.log`
- addition of a new log
- disabling the feature altogether

As @initconf pointed out, changing the `conn.log` has the potential to break a lot of downstream processing, no matter how many thoughts we put into the design. Hence, it would make sense to allow to opt-out. At the same time, adding a new log should be easy and could help to make the info still available to users that need to opt-out of the `conn.log` changes.

---

Some more thoughts/remarks on what @initconf brought up:

- There is already an `unknown_protocols.log` at the packet analyzer level 😉 
https://docs.zeek.org/en/master/scripts/policy/misc/unknown-protocols.zeek.html

- The semantics for `conn.log` fields are already fuzzy. For example, we encode ICMP type and code in ports. Likewise, artificially sessionizing ICMP and UDP impacts the other columns mentioned.

- Regarding additional information in a new log: As I understand, the idea is to just add an abstract and deliberatly vague summary of IP-based communication relations that Zeek is unable to analyze in detail. So probably there isn't much information to add from IP headers.

- If we add analyzers for new transport protocols, I believe we would have both, a new log and a new type of `conn.log` entries.

- Indeed, long running sessions would be easy to miss. However, this is a known problem and we do have https://github.com/corelight/zeek-long-connections to address this.

So all in all, I'd opt for the adapted `conn.log` as the new default and have policy scripts to opt-out and/or add a new log.

**Comment by stevesmoot** [comment] 2024-10-14 23:03
I'm not in favor of a wholly new log.  Given the above insight about policy and similarity in purpose and intent, I'd default to the existing unknown-protocols log, add optional fields we can snarf from IP header, and policy option to put in conn proto (which I think means we also need to extend the ENUM to handle the 256 values).  I dont have a firm opinion on numbers vs names & numbers-for-unknown.

**Comment by timwoj** [comment] 2024-11-07 19:25
Would it be alright to just move all of it to the policy? Instead of having a ID field in conn.log and a policy that adds a name field, the policy would just add both the ID and the name field.

**Comment by ckreibich** [comment] 2024-11-11 06:39
We've talked further and we'll stick with the original approach. conn.log makes sense since it's the default hub for Zeek's logging, and I also remain in favor of the new column — it is simple and intuitive, unencumbered from past decisions around transport-level enums, addresses the need to see additional IP protocol activity, and is easy enough to ignore. 
We'll include a policy script to suppress the new field for folks who really don't want it.

Once actual issues come up when this has landed, we can iterate further. 7.1 is a great time to get this in because it allows 7.2 for potential corrections.

Thanks for iterating on the PR Tim, will review asap.

**Closed** 2024-11-13 21:36 UTC
