### ISSUE TITLE
zkg ignores sufficiently high spicyz version that is already installed

### ISSUE THREAD

**Issue by ynadji** [zeek/zeek#2519] opened 2022-11-01 13:36 UTC
The snippet below shows the issue: a package requires spicy-plugin of a certain version, I already have that requirement satisfied, but `zkg` will try to install a newer version of the spicy-plugin anyway. Not sure why this is ignored.

```
$ zkg --version
zkg 2.13.0

$ zeek --version
zeek version 5.1.0-dev.497

$ cat icsnpp-genisys/zkg.meta
[package]
summary = Genisys is a protocol defined by Union Switch & Signal for communicating with SCADA field devices, commonly used in the railway industry.
...
depends =
  zkg >=2.12.0
  zeek >=3.0.0
  spicy-plugin >=1.3.0

...

$ spicyz --version
1.3.17

$ zkg install icsnpp-genisys
The following packages will be INSTALLED:
  zeek/cisagov/icsnpp-genisys (main)

The following dependencies will be INSTALLED:
  zeek/zeek/spicy-plugin (v1.4.0)

Proceed? [Y/n] n
Abort.
```

Here's the error when it tries to install on a different machine:

```
#12 49.70 Installing "zeek/zeek/spicy-plugin"Exception in thread Thread-1:
#12 195.4 Traceback (most recent call last):
#12 195.4   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
#12 195.4     self.run()
#12 195.4   File "/usr/local/bin/zkg", line 481, in run
#12 195.4     self.error = self.manager.install(
#12 195.4   File "/usr/local/lib/python3.8/dist-packages/zeekpkg/manager.py", line 2694, in install
#12 195.4     return self._install(matches[0], version)
#12 195.4   File "/usr/local/lib/python3.8/dist-packages/zeekpkg/manager.py", line 2768, in _install
#12 195.4     fail_msg = self._stage(package, version, clone, stage)
#12 195.4   File "/usr/local/lib/python3.8/dist-packages/zeekpkg/manager.py", line 2624, in _stage
#12 195.4     make_symlink(full_path, os.path.join(
#12 195.4   File "/usr/local/lib/python3.8/dist-packages/zeekpkg/_util.py", line 66, in make_symlink
#12 195.4     raise error
#12 195.4   File "/usr/local/lib/python3.8/dist-packages/zeekpkg/_util.py", line 60, in make_symlink
#12 195.4     os.symlink(target_path, link_path)
#12 195.4 FileExistsError: [Errno 17] File exists: '/root/.zkg/clones/package/spicy-plugin/build/bin/spicyz' -> '/opt/corelight/bin/spicyz'
#12 195.4 
#12 195.4 Traceback (most recent call last):
#12 195.4   File "/usr/local/bin/zkg", line 2770, in <module>
#12 195.4     main()
#12 195.4   File "/usr/local/bin/zkg", line 2767, in main
#12 195.4     args.run_cmd(manager, args, config, configfile)
#12 195.4   File "/usr/local/bin/zkg", line 746, in cmd_install
#12 195.4     print('Installed "{}" ({})'.format(name, ipkg.status.current_version))
#12 195.4 AttributeError: 'NoneType' object has no attribute 'status'
```

**Comment by awelzel** [comment] 2022-11-02 12:28
> I already have that requirement satisfied, but zkg will try to install a newer version of the spicy-plugin anyway. Not sure why this is ignored.

Is the requirement satisfied because you have spicy-plugin builtin? Is (minimally the first part) your report a duplicate of the following ticket?

https://github.com/zeek/zeek/issues/2243

**Closed** 2022-11-02 13:55 UTC
