### ISSUE TITLE
Rare occurances of incorrect fields filled in SMTP log record

### ISSUE THREAD

**Issue by initconf** [zeek/zeek#254] opened 2019-01-24 20:12 UTC
This is quite rare occurrence and I am not exactly sure how to replicate it either. 

I have noticed that there are rare times when two different emails are combined into one single SMTP record. I base this on the fact that I verified that emails were different using timemachine captures. 

the incorrect SMTP log records sender of one email populated with recipients of one (or both) emails - then subject of one of the emails (generally the first one).

My hypothesis is that there might be packet drops resulting in zeek not understanding that these are two different emails on same TCP stream - but I speculate. 

I will try to figure out a way to reproduce this and/or see if I can help further with zero'ing on the specifics of the issue. (Sorry this is a bit generic )

Message me offline and I can send you exact log entries if desired.

**Comment by mdtro** [comment] 2019-11-27 17:46
I believe we might be having a similar issue with _cc_ and _mailfrom_ fields bleeding over. It's also very rare for us and I'm uncertain how to recreate this.

@initconf, when you refer to the recipients being mixed up in the _rcptto_ fields or _to_? From what I'm seeing it seems to be isolated to fields in the SMTP envelope?

**Comment by rsmmr** [comment] 2020-08-12 08:50
@initconf were you ever able to get a packet trace reproducing this?

**Comment by rsmmr** [comment] 2020-11-03 14:31
@initconf ping

**Comment by rsmmr** [comment] 2020-11-06 11:06
I'll close this one as next steps are unclear. Please reopen if there's new information.

**Closed by rsmmr** 2020-11-06 11:06 UTC
Labels: Area: Protocol Analysis, Type: Bug :bug:
