### ISSUE TITLE
Behavior of record construction changed in 4.1

### ISSUE THREAD

**Issue by JustinAzoff** [zeek/zeek#1987] opened 2022-02-28 13:50 UTC
```
type info : record {
    str:   string    &log ;
    cnt:   count     &log ;
} &log;

event zeek_init()
{
    local resp = info(
        $str="hello"
    );
    print(resp);
}
```

This used to fail, but now works, leaving the non optional cnt uninitialized:

```
$ tryzeek -V 4.0.0 ./record_missing.zeek 
error in ././try.zeek, lines 8-10: non-optional field "cnt" missing ((coerce [$str=hello] to info))
```

```
$ tryzeek -V 4.1.0 ./record_missing.zeek 
[str=hello, cnt=<uninitialized>]
```

@vpax mentioned this may be related to "more efficient record constructors".

**Comment by vpax** [comment] 2022-02-28 16:59
I've implemented a fix for this.  Note that it requires a change to the base scripts, per the attached file.  This makes me think that we probably should make this a warning and not an error, so it doesn't break existing code.

[incomplete-rec-constructor.patch.txt](https://github.com/zeek/zeek/files/8155170/incomplete-rec-constructor.patch.txt)

**Comment by 0xxon** [comment] 2022-02-28 18:28
That's an interesting question. Since this is a regression that was only introduced with 4.1, I think we can just go ahead and immediately change the behavior to an error.

To my knowledge, our deprecation/backwards stability guarantees only cover behavior that was seen in an LTS release - so a behavior that exists in 4.0 has to be deprecated in 5.0 and can then be removed. However, any behavior that only exists in a feature release (4.x with x>0) comes with no guarantees as long as it never made it into an LTS release.

Furthermore - this is a really easy script fix in these cases.

**Comment by vpax** [comment] 2022-02-28 18:34
> Since this is a regression that was only introduced with 4.1, I think we can just go ahead and immediately change the behavior to an error.

Ah, good point.  I was thinking the fix somehow affected older code because it found a problem in the base scripts - but it turns out that that change (in the base scripts) was a recent introduction.

I'll go ahead and put together PR that generates an error.

**Closed** 2022-03-02 13:53 UTC
