### ISSUE TITLE
Zeek Segfault during TCP reassembly

### ISSUE THREAD

**Issue by newton-o** [zeek/zeek#2438] opened 2022-09-26 17:58 UTC
segfault stack trace:
std::_Rb_tree_rebalance_for_erase(std::_Rb_tree_node_base*, std::_Rb_tree_node_base&)
zeek::DataBlockList::Delete(std::_Rb_tree_const_iterator<std::pair<unsigned long const, zeek::DataBlock> >)
zeek::DataBlockList::Trim(unsigned long, unsigned long, zeek::DataBlockList*)
zeek::analyzer::tcp::TCP_Reassembler::AckReceived(unsigned long)
zeek::packet_analysis::TCP::TCPSessionAdapter::Process(bool, tcphdr const*, int, std::shared_ptr<zeek::IP_Hdr> const&, unsigned char const*, int)
zeek::packet_analysis::TCP::TCPAnalyzer::DeliverPacket(zeek::Connection*, double, bool, int, zeek::Packet*)
zeek::packet_analysis::IP::IPBasedAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*)
zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const
zeek::packet_analysis::IP::IPAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*)
zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const
zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const
zeek::packet_analysis::Manager::ProcessPacket(zeek::Packet*)
zeek::run_state::detail::dispatch_packet(zeek::Packet*, zeek::iosource::PktSrc*)
zeek::iosource::PktSrc::Process()
zeek::run_state::detail::run_loop()
main
__libc_start_main
_start

**Comment by awelzel** [comment] 2022-09-27 07:54
Hey - thanks for the report.

This isn't very actionable unfortunately. It would help to see some local variable values and DataBlockList member values during `Trim()` and `Delete()` to understand if anything looks completely off. Whether the segfault happened for a null pointer or a wild pointer might also help.

Do you have a coredump where you could extract that information? 

Does this happen regularly enough to track this down?

**Comment by newton-o** [comment] 2022-09-27 16:54
Here's an internal reference to the original issue: https://jira.corelight.io/browse/NTI-2158.  As I understand, it has only happened that once and we do not have a pcap for it.

**Comment by awelzel** [comment] 2022-09-29 14:52
@newton-o , I'm going to close this due to not being very actionable. Please re-open if you have more pointers or in the best case a reliable reproducers that can be shared publicly.

**Closed by awelzel** 2022-09-29 14:52 UTC
