### ISSUE TITLE
zeekctl start error

### ISSUE THREAD

**Issue by Wapiti08** [zeek/zeek#840] opened 2020-03-03 09:10 UTC
```
[ZeekControl] > deploy
checking configurations ...
zeek scripts failed.
fatal error in /usr/local/zeek/share/zeek/base/init-bare.zeek, line 1: Failed to initialize kqueue: Invalid argument
```
The first line in init-bare.zeek is:
```
@load base/bif/const.bif
@load base/bif/types.bif
```
I tried to modify the const.bif to const.bif.zeek. It did not work. Can you help me with this error?

**Comment by JustinAzoff** [comment] 2020-03-04 01:14
What OS is this on?  What does your node.cfg contain?

**Comment by Wapiti08** [comment] 2020-03-04 02:39
Ubuntu 16.04
And  the context is node.cfg:
```
[zeek]
type=standalone
host=localhost
interface=eth2
```

I checked the name of network configuration with ifconfig.

**Comment by Wapiti08** [comment] 2020-03-04 03:25
By the way, I do not think it is the error with interface. I tried both the wrong name eth0 and right one eth1, I got the same error

**Comment by 0xxon** [comment] 2020-03-04 22:00
Closing since this is a duplicate of #842 - and the discussion is continued there.

**Closed by 0xxon** 2020-03-04 22:00 UTC
