### ISSUE TITLE
Record type-checking doesn't catch reuse of field names

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#2105] opened 2022-05-13 21:55 UTC
The following Zeek script:

> type r: record {
        a: count;
        a: string;
};
>
> global x:r;
>
> x$a = 3;
print x;

prints `[a=3, a=<uninitialized>]` ... !

**Comment by 0xxon** [comment] 2022-05-17 15:47
This is a duplicate of https://github.com/zeek/zeek/issues/1628

**Closed by 0xxon** 2022-05-17 15:47 UTC
Labels: Type: Bug :bug:, Area: Scripting
