### ISSUE TITLE
Recent @if...&analyze change breaks zeekctl tests

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#3093] opened 2023-05-26 23:23 UTC
See https://cirrus-ci.com/task/4808355248603136. The short gist is this:

```
[ #5] command.scripts ... failed
  % 'TEST_DIFF_CANONIFIER=$SCRIPTS/diff-remove-timestamps-yyyy-mm-dd-hh-mm-ss btest-diff all.out' failed unexpectedly (exit code 1)
  % cat .diag
  == File ===============================
  manager scripts are ok.
    warning in /zeek/auxil/zeekctl/build/testing/test.25922/share/zeek/base/frameworks/cluster/./nodes/manager.zeek, line 22: @if &analyze inside conditional
    warning in /zeek/auxil/zeekctl/build/testing/test.25922/share/zeek/base/frameworks/cluster/./nodes/logger.zeek, line 67: @if &analyze inside conditional
    warning in /zeek/auxil/zeekctl/build/testing/test.25922/share/zeek/base/frameworks/cluster/./broker-stores.zeek, line 21: @if &analyze inside conditional
    warning in /zeek/auxil/zeekctl/build/testing/test.25922/share/zeek/base/frameworks/cluster/./broker-stores.zeek, line 25: @if &analyze inside conditional
    warning in /zeek/auxil/zeekctl/build/testing/test.25922/share/zeek/base/frameworks/intel/./cluster.zeek, line 20: @if &analyze inside conditional
    warning in /zeek/auxil/zeekctl/build/testing/test.25922/share/zeek/base/frameworks/intel/./cluster.zeek, line 24: @if &analyze inside conditional
    warning in /zeek/auxil/zeekctl/build/testing/test.25922/share/zeek/base/frameworks/intel/./cluster.zeek, line 76: @if &analyze inside conditional
    warning in /zeek/auxil/zeekctl/build/testing/test.25922/share/zeek/base/frameworks/intel/./cluster.zeek, line 97: @if &analyze inside conditional
    warning in /zeek/auxil/zeekctl/build/testing/test.25922/share/zeek/base/frameworks/sumstats/./cluster.zeek, line 62: @if &analyze inside conditional
    warning in /zeek/auxil/zeekctl/build/testing/test.25922/share/zeek/base/frameworks/sumstats/./cluster.zeek, line 210: @if &analyze inside conditional
    warning in /zeek/auxil/zeekctl/build/testing/test.25922/share/zeek/base/frameworks/openflow/./cluster.zeek, line 16: @if &analyze inside conditional
    warning in /zeek/auxil/zeekctl/build/testing/test.25922/share/zeek/base/frameworks/openflow/./cluster.zeek, line 52: @if &analyze inside conditional
    warning in /zeek/auxil/zeekctl/build/testing/test.25922/share/zeek/base/frameworks/netcontrol/./cluster.zeek, line 19: @if &analyze inside conditional
    warning in /zeek/auxil/zeekctl/build/testing/test.25922/share/zeek/base/frameworks/netcontrol/./cluster.zeek, line 96: @if &analyze inside conditional
    warning in /zeek/auxil/zeekctl/build/testing/test.25922/share/zeek/base/frameworks/netcontrol/./cluster.zeek, line 150: @if &analyze inside conditional
    warning in /zeek/auxil/zeekctl/build/testing/test.25922/share/zeek/base/frameworks/telemetry/./cluster.zeek, line 15: @if &analyze inside conditional
  <...paths...>
```

My assumption is because those scripts are being loaded by another script with an `@if` in it, and therefore blowing up.

**Comment by vpax** [comment] 2023-05-26 23:29
Ugh.  I guess step 1 is to figure out what that script is, assuming that's the cause.

**Comment by timwoj** [comment] 2023-05-26 23:31
We probably should make that build part of the default set of CI builds, instead of making it conditional on a label on the PR.

**Comment by awelzel** [comment] 2023-05-27 10:59
>> Ugh. I guess step 1 is to figure out what that script is, assuming that's the cause.

> We probably should make that build part of the default set of CI builds, instead of making it conditional on a label on the PR.

I'd think differently. This is missing test coverage in base Zeek. It's not for zeekctl integration tests to cover those things as a side-effect. IMO the process worked: Issues were found after a merge to master and we can/should figure out ways to detect them earlier in Zeek directly.

Running the following zeek invocation starting up just a manager node with the latest container image already reproduces the splash of warnings outside of any zeekctl usage:
```
$ docker run --rm -it -v $(pwd):/test -w /test zeek/zeek-dev
root@e0e30b41ef5f:/test# cat cluster-layout.zeek
redef Cluster::nodes = {
    ["manager"] = [$node_type=Cluster::MANAGER, $ip=127.0.0.1, $p=to_port("10000/tcp")],
};
root@e0e30b41ef5f:/test# CLUSTER_NODE=manager zeek
warning in /usr/local/zeek/share/zeek/base/frameworks/cluster/./nodes/manager.zeek, line 22: @if &analyze inside conditional
warning in /usr/local/zeek/share/zeek/base/frameworks/cluster/./nodes/logger.zeek, line 67: @if &analyze inside conditional
warning in /usr/local/zeek/share/zeek/base/frameworks/cluster/./broker-stores.zeek, line 21: @if &analyze inside conditional
warning in /usr/local/zeek/share/zeek/base/frameworks/cluster/./broker-stores.zeek, line 25: @if &analyze inside conditional
warning in /usr/local/zeek/share/zeek/base/frameworks/intel/./cluster.zeek, line 20: @if &analyze inside conditional
warning in /usr/local/zeek/share/zeek/base/frameworks/intel/./cluster.zeek, line 24: @if &analyze inside conditional
warning in /usr/local/zeek/share/zeek/base/frameworks/intel/./cluster.zeek, line 76: @if &analyze inside conditional
warning in /usr/local/zeek/share/zeek/base/frameworks/intel/./cluster.zeek, line 97: @if &analyze inside conditional
warning in /usr/local/zeek/share/zeek/base/frameworks/sumstats/./cluster.zeek, line 62: @if &analyze inside conditional
warning in /usr/local/zeek/share/zeek/base/frameworks/sumstats/./cluster.zeek, line 210: @if &analyze inside conditional
warning in /usr/local/zeek/share/zeek/base/frameworks/openflow/./cluster.zeek, line 16: @if &analyze inside conditional
warning in /usr/local/zeek/share/zeek/base/frameworks/openflow/./cluster.zeek, line 52: @if &analyze inside conditional
warning in /usr/local/zeek/share/zeek/base/frameworks/netcontrol/./cluster.zeek, line 19: @if &analyze inside conditional
warning in /usr/local/zeek/share/zeek/base/frameworks/netcontrol/./cluster.zeek, line 96: @if &analyze inside conditional
warning in /usr/local/zeek/share/zeek/base/frameworks/netcontrol/./cluster.zeek, line 150: @if &analyze inside conditional
warning in /usr/local/zeek/share/zeek/base/frameworks/telemetry/./cluster.zeek, line 15: @if &analyze inside conditional
```

Here's an idea for a "test-all-policy-cluster" test that will catch these by loading "test-all-policy" in cluster mode using the usual node types (it generates some more warnings the the ones shown above):

```
diff --git a/testing/btest/coverage/test-all-policy-cluster.test b/testing/btest/coverage/test-all-policy-cluster.test
new file mode 100644
index 000000000..b0667d474
--- /dev/null
+++ b/testing/btest/coverage/test-all-policy-cluster.test
@@ -0,0 +1,40 @@
+# @TEST-DOC: Start each node type and ensure there are no unexpected warnings to be seen
+#
+# @TEST-PORT: BROKER_PORT1
+# @TEST-PORT: BROKER_PORT2
+# @TEST-PORT: BROKER_PORT3
+# @TEST-PORT: BROKER_PORT4
+#
+# @TEST-EXEC: CLUSTER_NODE=manager zeek %INPUT
+# @TEST-EXEC: CLUSTER_NODE=logger-1 zeek %INPUT
+# @TEST-EXEC: CLUSTER_NODE=proxy-1 zeek %INPUT
+# @TEST-EXEC: CLUSTER_NODE=worker-1 zeek %INPUT
+# @TEST-EXEC: TEST_DIFF_CANONIFIER='grep -v "scan.zeek.*deprecated script"' btest-diff .stderr
+
+@load base/frameworks/cluster
+@load test-all-policy
+
+@TEST-START-FILE cluster-layout.zeek
+redef Cluster::nodes = {
+       ["manager"]  = [$node_type=Cluster::MANAGER, $ip=127.0.0.1, $p=to_port(getenv("BROKER_PORT1"))],
+       ["logger-1"] = [$node_type=Cluster::LOGGER,  $ip=127.0.0.1, $p=to_port(getenv("BROKER_PORT2")), $manager="manager"],
+       ["proxy-1"]  = [$node_type=Cluster::PROXY,   $ip=127.0.0.1, $p=to_port(getenv("BROKER_PORT3")), $manager="manager"],
+       ["worker-1"] = [$node_type=Cluster::WORKER,  $ip=127.0.0.1, $p=to_port(getenv("BROKER_PORT4")), $manager="manager"],
+};
+
+@TEST-END-FILE
+
+# Make this a single-node cluster-layout so no connection attempts happen
+# to other nodes.
+redef Cluster::nodes = {
+       [Cluster::node] = Cluster::nodes[Cluster::node],
+};
+
+# Avoid rotation commands to be executed.
+redef Log::default_rotation_interval = 0sec;
+
+event zeek_init()
+       {
+       print Cluster::node, "zeek_init()";
+       terminate();
+       }
```

Unfortunately I'm less confident about fixes here. Top-level `cluster/__load__.zeek` is not using `if &analyze` when I think it should. Pattern matching the warnings: @vpax , did you maybe skip leveraging `@if &analyze` in `__load__zeek` files? Maybe for reasons?

**Comment by awelzel** [comment] 2023-06-07 13:44
Closing. This isn't an issue anymore as the feature was reverted. The test suite was extended with above test to catch it next time around.

**Closed by awelzel** 2023-06-07 13:44 UTC
