### ISSUE TITLE
Error when install zeek 6 on centos 7 with source file

### ISSUE THREAD

**Issue by sanojsa** [zeek/zeek#3425] opened 2023-11-01 06:27 UTC
Got below error while installing zeek 6.0.1 on centos 7 using source file.

I have used GCC version  9.3.1

Error
===

/root/installzeek/zeek-6.0.1/auxil/spicy/hilti/runtime/include/hilti/rt/types/integer.h:63:79: error: expected ‘)’ before ‘PRIu16
error: expected primary-expression before ‘(’ token
  326 |             throw IndexError(fmt("vector index %" PRIu64 " out of range", i));

**Comment by bbannier** [comment] 2023-11-01 07:15
Could you please add some more detail on how we can reproduce this error?

- how did you install Zeek?
- What command do we need to invoke to see this error?

**Comment by sanojsa** [comment] 2023-11-01 07:33
Manually downloaded source code (.tar.gz) from https://zeek.org/get-zeek/ and build, try to install

./configure --prefix=/root/zeek
make
make install

**Comment by bbannier** [comment] 2023-11-01 09:39
I cannot reproduce this, so I suspect it must be something specific to your environment. To diagnose this further we would need to know more details about how you set it up.

What worked for me was the following:

- use the Zeek CI centos-7 `Dockerfile` with modifications:
  - remove line with unmaintained mirror, https://github.com/zeek/zeek/blob/v6.0.1/ci/centos-7/Dockerfile#L16
  - use `devtoolset-9` by adjusting https://github.com/zeek/zeek/blob/v6.0.1/ci/centos-7/Dockerfile#L30 and https://github.com/zeek/zeek/blob/v6.0.1/ci/centos-7/Dockerfile#L61

  I then build the image with `docker build -t wip ci/centos-7`.

- In that container (`docker run -it wip`):
  - install a recent CMake

     ```console
     yum install -y wget
     cd
     wget https://github.com/Kitware/CMake/releases/download/v3.27.7/cmake-3.27.7-linux-x86_64.tar.gz
     tar xf cmake-3.27.7-linux-x86_64.tar.gz
     export PATH=$HOME/cmake-3.27.7-linux-x86_64/bin:$PATH
     ```

  - download and build zeek-6.0.1:

    ```console
    wget https://download.zeek.org/zeek-6.0.1.tar.gz
    tar xf zeek-6.0.1.tar.gz
    cd zeek-6.0.1
    ./configure
    make -j$(nproc)
    ```

**Comment by awelzel** [comment] 2023-11-17 19:05
@sanojsa - I'm closing this ticket. We're currently testing CentOS 7 in CI successfully. If you need further support please start a new thread in the [forum or join on Slack and ask in #development or #general](https://zeek.org/community/).

Further note that CentOS 7.0 will be EOL in a few months. Consider switching to a more modern distribution.

**Closed by awelzel** 2023-11-17 19:05 UTC
