### ISSUE TITLE
CI: build failures in macOS Monterey

### ISSUE THREAD

**Issue by AmazingPP** [zeek/zeek#2465] opened 2022-10-09 08:28 UTC
The `macos_monterey` ci task often fails in the build stage.

```make
[  8%] Building CXX object auxil/broker/caf/libcaf_core/CMakeFiles/libcaf_core_obj.dir/src/actor_profiler.cpp.o
/tmp/zeek/build/auxil/spicy/spicy/3rdparty/justrx/justrx/autogen/re-parse.c:712:2: error: unterminated conditional directive
#if RE_DEBUG
 ^
src/re-parse.y:3:2: error: unterminated conditional directive
#ifndef __clang_analyzer__
 ^
2 errors generated.
make[2]: *** [auxil/spicy/spicy/3rdparty/justrx/CMakeFiles/jrx-objects.dir/justrx/autogen/re-parse.c.o] Error 1
make[1]: *** [auxil/spicy/spicy/3rdparty/justrx/CMakeFiles/jrx-objects.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

https://cirrus-ci.com/task/4964559944417280?logs=build#L883

**Comment by bbannier** [comment] 2022-10-09 10:07
Since this wasn't seen in previous CI runs and nothing in #2450 touched Spicy-related files I restarted the failing CI job and it now passed. This seems to indicate some sort of transient failure to me, and I am closing this issue. Please reopen it if you see it again.

**Comment by AmazingPP** [comment] 2022-10-09 11:28
In fact, I found that the same failure occurred many times in the last two weeks.

https://cirrus-ci.com/task/5067734923870208?logs=build#L887
https://cirrus-ci.com/task/5780970933583872?logs=build#L880
https://cirrus-ci.com/task/4600277578809344?logs=build#L864
https://cirrus-ci.com/task/5255697456693248?logs=build#L863

**Comment by bbannier** [comment] 2022-10-09 12:28
> In fact, I found that the same failure happened many times.

Thanks for digging in, that's definitely weird and worth looking into in more detail.

**Comment by timwoj** [comment] 2022-10-09 15:41
Duplicate of https://github.com/zeek/zeek/issues/2408

**Closed by timwoj** 2022-10-09 15:41 UTC
