### ISSUE TITLE
`has no symbols` warnings

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#2159] opened 2022-06-03 10:04 UTC
I'm seeing a number of `ranlib` reports on macOS with current master (technically, this is `topic/christian/management-instance-handling`, but imagine it's the same with master);

```
[476/1772] Linking CXX static library auxil/spicy/spicy/lib/libhilti.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/spicy/spicy/lib/libhilti.a(utf.posix.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/spicy/spicy/lib/libhilti.a(utf.posix.c.o) has no symbols
[562/1772] Linking CXX static library auxil/spicy/spicy/lib/libspicy.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/spicy/spicy/lib/libspicy.a(utf.posix.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/spicy/spicy/lib/libspicy.a(utf.posix.c.o) has no symbols
[677/1772] Linking CXX static library auxil/broker/caf/libcaf_core/libcaf_core.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/broker/caf/libcaf_core/libcaf_core.a(dummy.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/broker/caf/libcaf_core/libcaf_core.a(dummy.cpp.o) has no symbols
[807/1772] Linking CXX static library auxil/broker/caf/libcaf_io/libcaf_io.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/broker/caf/libcaf_io/libcaf_io.a(dummy.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/broker/caf/libcaf_io/libcaf_io.a(dummy.cpp.o) has no symbols
[855/1772] Linking CXX static library auxil/broker/caf-incubator/libcaf_net/libcaf_net.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/broker/caf-incubator/libcaf_net/libcaf_net.a(dummy.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/broker/caf-incubator/libcaf_net/libcaf_net.a(dummy.cpp.o) has no symbols
[953/1772] Linking C static library auxil/c-ares/lib/libcares.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/c-ares/lib/libcares.a(ares_android.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/c-ares/lib/libcares.a(ares_getenv.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/c-ares/lib/libcares.a(ares_platform.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/c-ares/lib/libcares.a(ares_strcasecmp.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/c-ares/lib/libcares.a(ares_writev.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/c-ares/lib/libcares.a(windows_port.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/c-ares/lib/libcares.a(ares_android.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/c-ares/lib/libcares.a(ares_getenv.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/c-ares/lib/libcares.a(ares_platform.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/c-ares/lib/libcares.a(ares_strcasecmp.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/c-ares/lib/libcares.a(ares_writev.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: auxil/c-ares/lib/libcares.a(windows_port.c.o) has no symbols
```

Anybody else seeing that? Something we can fix (probably individually)?

**Comment by vpax** [comment] 2022-06-03 15:16
Yes I've been seeing that too.

**Comment by timwoj** [comment] 2022-06-03 17:59
macOS's `libtool` command has an argument for this called `-no_warning_for_no_symbols`, but the problem is that most of these come from third-party libraries so we have to be able to override their usage of it.

**Comment by vpax** [comment] 2022-06-03 19:49
Just did a fresh build (well, Master as of a few days ago) and also got these messages under MacOS Big Sur:

> In file included from ../auxil/broker/caf-incubator/libcaf_net/caf/net/length_prefix_framing.hpp:17:
../auxil/broker/caf-incubator/libcaf_net/caf/net/message_flow_bridge.hpp:46:7: warning: field 'in_res_' will be initialized after field 'trait_' [-Wreorder-ctor]
    : in_res_(std::move(in_res)),
      ^

(with a bunch of info about template expansions, I think, that led to that)

**Comment by timwoj** [comment] 2022-06-03 20:19
Yep, that's https://github.com/zeek/broker/issues/232.

**Comment by timwoj** [comment] 2022-06-26 19:14
I opened https://github.com/c-ares/c-ares/pull/474 to fix the warnings from c-ares. It looks like CAF will probably need similar fixes.

**Comment by timwoj** [comment] 2023-04-12 23:53
This seems to have resolved itself in the interim. Feel free to reopen this if it pops up again.

**Closed by timwoj** 2023-04-12 23:53 UTC
