### ISSUE TITLE
Spicy analyzer build files are not cached by ccache

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#4133] opened 2024-12-16 22:44 UTC
It looks like the output from a build of a Spicy analyzer (or at least our internal ones) isn't being cached by ccache. A build with `--ccache` will rebuild/relink those files again after a `make clean`.

**Comment by bbannier** [comment] 2024-12-17 09:31
For our internal analyzers we (1) [generate C++ files](https://github.com/zeek/cmake/blob/85c6f90f238b5851edbd6b6962f44de34833a76c/BuiltInSpicyAnalyzer.cmake#L74-L85
). These source files are then [bundled into a CMake `OBJECT` library](https://github.com/zeek/cmake/blob/85c6f90f238b5851edbd6b6962f44de34833a76c/BuiltInSpicyAnalyzer.cmake#L88) (really just a way to refer to a set of object files) and [linked into Zeek](https://github.com/zeek/cmake/blob/85c6f90f238b5851edbd6b6962f44de34833a76c/BuiltInSpicyAnalyzer.cmake#L98-L99) like any other C++ source. 

Since there is nothing particular about these generated C++ sources their compilation to `*.o` files (the part involving a C++ compiler) could and should be cached by `ccache`; I confirmed that this works for me on my machine™️.  For the target generating the C++ files we [add an explicit dependency](https://github.com/zeek/cmake/blob/85c6f90f238b5851edbd6b6962f44de34833a76c/BuiltInSpicyAnalyzer.cmake#L77) on both the analyzer's input files (`*.spicy` and `*.evt` files) as well as `spicyz` itself; if any of these change (likely for most build systems: their access time changed) the C++ sources are regenerated, and `spicyz` has no magic caching mechanism to short-circuit that (I guess similar to e.g., `bifcl` or `binpac` would behave). The subsequent compilation of these can go through `ccache` again.

> A build with `--ccache` will rebuild/relink those files again after a make clean.

Unless I am missing something a build with `--ccache` should always relink since it can only cache single object files.

I am closing since it is not clear whether anything needs to be done. Please feel free to reopen with more info.

**Closed by bbannier** 2024-12-17 09:31 UTC
Labels: Type: Bug :bug:, Area: Build/Platform

**Comment by awelzel** [comment] 2024-12-17 09:44
> I am closing since it is not clear whether anything needs to be done. Please feel free to reopen with more info.

Not re-opening, but to add `ccache -s` for me doesn't show any misses when rebuilding.

I had this suspicion previously, too, but I believe it's just the `spicyz` invocations that may take a bit and then give the impression that caching isn't in effect. `bifcl` and `binpac` are essentially instant in comparison.

**Comment by bbannier** [comment] 2024-12-17 09:49
> I had this suspicion previously, too, but I believe it's just the `spicyz` invocations that may take a bit and then give the impression that caching isn't in effect. `bifcl` and `binpac` are essentially instant in comparison.

Definitely. We explicitly [made CMake output slightly more verbose](https://github.com/zeek/cmake/blob/85c6f90f238b5851edbd6b6962f44de34833a76c/BuiltInSpicyAnalyzer.cmake#L78) so that there is some indication what is being worked on, e.g., when building with `ninja` without `-v` one could see something like

```
[0/8] Compiling LDAP analyzer
```

This indicates "compilation" from Spicy sources to C++.
