### ISSUE TITLE
The `--include-plugins` parameter can't be used for the spicy analyzer

### ISSUE THREAD

**Issue by AmazingPP** [zeek/zeek#4002] opened 2024-11-02 03:12 UTC
I have `spicy-config` in `PATH`, but cmake tells me it's missing.

```bash
$ which spicy-config
/opt/zeek/bin/spicy-config
$ ./configure --prefix=/opt/zeek --include-plugins='/usr/src/spicy-foo'
......
-- spicyz: /opt/zeek/bin/spicyz
-- Zeek plugin version: 7.0.3
-- Zeek plugin CMake path: /opt/zeek/share/zeek/cmake
-- Found zeek-config: /usr/src/zeek/build/zeek-config
-- Found Zeek: yes  
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Spicy (missing: SPICY_CONFIG)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /opt/zeek/share/zeek/cmake/FindSpicy.cmake:183 (find_package_handle_standard_args)
  /usr/src/spicy-foo/cmake/FindSpicyPlugin.cmake:70 (find_package)
  /usr/src/spicy-foo/CMakeLists.txt:6 (find_package)


-- Configuring incomplete, errors occurred!
See also "/usr/src/zeek/build/CMakeFiles/CMakeOutput.log".
See also "/usr/src/zeek/build/CMakeFiles/CMakeError.log".
```

For more discussion details, please refer to Slack: https://zeekorg.slack.com/archives/CSZBXF6TH/p1730364390559499

**Comment by awelzel** [comment] 2024-11-04 08:22
Duplicate of https://github.com/zeek/zeek/issues/2442.

And it's not clear to me `--include-plugins` should support this, or this might be easier via a separate `--include-spicy-analyzer`

**Comment by 0xxon** [comment] 2024-11-14 12:25
Closing - discussion should just take place in #2442

**Closed by 0xxon** 2024-11-14 12:25 UTC
