### ISSUE TITLE
How to output current time in errors and warnings instead of network time?

### ISSUE THREAD

**Issue by simonhf** [zeek/zeek#1054] opened 2020-07-08 18:57 UTC
**Background and assumptions:**

My understanding is that 'current time' is effectively the wall clock time and ticks up with the resolution of the underlying hardware of the computer running Zeek, even in-between receiving packets.

Whereas 'network time' is set as each PCAP / trace packet is read and is set to the timestamp of the packet.

Therefore 'network time' does not tick up in-between PCAP / trace packets being read.

So 'network time' is useful because a PCAP / trace file might contain a few packets which get processed in a few milliseconds current time but the PCAP / trace file packet timestamps might span many minutes / hours. Let's imagine that PCAP / trace packet #x has timestamp y, and packet #x+1 has timestamp y+5 minutes. Zeek needs to know the network time difference between the packets to e.g. consider if some type of protocol logic relating to the packets has 'timed out' etc.

**The default Zeek functionality:**

If Zeek is reading from a live NIC then errors and signal log lines will be prefixed by current time.

However, if Zeek is reading from a PCAP /trace file then errors and signal log lines will be prefixed by network time.

**The issue:**

If you are developing new Zeek functionality e.g. as a Zeek C/C++ plugin and/or Zeek script, then you might want to output your own logs for debugging with a timestamp prefix to show exactly when the log line was output.

This is especially important if dealing with multiple Zeek processes since code might run almost or at the same time if the hardware running the Zeek instances has multiple CPUs.

**Example:**

Here the log lines output by a Zeek script are prefixed by current time, whereas the errors and signal log lines are prefixed by network time.

This is confusing (because of the switch between current time and network item) but usable as as single output file.

But if trying to combine multiple Zeek output files then it becomes difficult to merge them into a single log of events at run-time. Whereas, if they were all prefixed with current time then you could just sort them together :-)

```
$ egrep --before-context=1 --after-context=1 "(termination signal|error)" run-term-signal-issue/timestamp-zeek.log | tail -11
--
1594230200.390124 [term-signal-issue.zeek] - 1361916160.126052    40=len packet=11261
1361916160.126168 expression error in ./../term-signal-issue.zeek, line 6: field value missing (p$ip)
1594230200.390268 [term-signal-issue.zeek] - 1361916160.126636   451=len packet=11263
--
1594230200.436803 [term-signal-issue.zeek] - 1361916160.432432   153=len packet=12087
1361916160.432710 expression error in ./../term-signal-issue.zeek, line 6: field value missing (p$ip)
1594230200.436906 [term-signal-issue.zeek] - 1361916160.433857    52=len packet=12089
--
1594230200.499999 [term-signal-issue.zeek] - 1361916160.954049   904=len packet=13382
1361916160.954049 received termination signal
```

**The question:**

Is there a way to get Zeek to output errors and signal notification *always* prefixed with current time instead of network time?

**Follow-up questions:**

Is there a way to get Zeek to output extra info too, e.g. PID and/or TID info, and network time in addition to current time?

Is there a way to change the seemingly hard-coded output format of `PLUGIN_DBG_LOG()` so that it can be compatible style-wise with logging elsewhere?

Is there a way to get multiple Zeek processes to automatically merge their debug log output into a single output file without having to log each instance to its own file and then attempt to merge the files after the instances have ended?

**Steps to reproduce:**

Build Zeek:

```
$ sudo apt-get install cmake make gcc g++ flex bison libpcap-dev libssl-dev python-dev swig zlib1g-dev ninja-build
$ git clone --recursive --branch v3.1.4 --single-branch https://github.com/zeek/zeek.git ; cd zeek/
$ make distclean && ./configure --build-type=Debug --enable-debug
$ make -j`nproc` 2>&1 | egrep --line-buffered -v "(Entering|Leaving)" | tee ./build/make-j`nproc`.log
$ cd build/
```

Create simple Zeek script producing many stderr log lines:

```
$ cat term-signal-issue.zeek
global stderr = open("/dev/stderr");
global packet_count = 0;

event new_packet(c: connection, p: pkt_hdr) {
    packet_count += 1;
    print stderr, fmt("%f [%-21s] - %f %5d=len packet=%d", current_time(), @FILENAME, network_time(), p$ip$len, packet_count);
}
```

Grab a PCAP file:

```
$ wget https://s3.amazonaws.com/tcpreplay-pcap-files/bigFlows.pcap
```

Run Zeek:

```
$ bash -v -x -s << 'EOF' 2>&1 $(: note: only bash has working jobs -p)
chmod +x zeek-path-dev.sh ; source ./zeek-path-dev.sh ; which zeek
export ZEEK_RUN_FOLDER=run-term-signal-issue ; rm -rf $ZEEK_RUN_FOLDER ; mkdir -p $ZEEK_RUN_FOLDER ; pushd $ZEEK_RUN_FOLDER
export ZEEK_SCRIPT_FILE=../term-signal-issue.zeek
export BASHLOAD_READER_GROUPS=2 ; rm -rf /dev/shm/BaShLoad.*/
zeek --debug plugin-Zeek-BaShLoad --readfile ../bigFlows.pcap $ZEEK_SCRIPT_FILE > timestamp-zeek.log 2>&1 &
BASH_PROCESS_GROUP_PIDS=`jobs -p | perl -lane 'push @a, $_; sub END{ printf qq[@a]; }'`
sleep 1 ; kill -INT $BASH_PROCESS_GROUP_PIDS ; wait $BASH_PROCESS_GROUP_PIDS
EOF
...
+ sleep 1
+ kill -INT 103027
+ wait 103027
```

Examine head of Zeek stderr output:

```
$ cat run-term-signal-issue/timestamp-zeek.log | head -5
1594228173.467806 [term-signal-issue.zeek] - 1361916155.953172  1154=len packet=1
1594228173.467867 [term-signal-issue.zeek] - 1361916155.953222  1154=len packet=2
1594228173.467886 [term-signal-issue.zeek] - 1361916155.953222    80=len packet=3
1594228173.468066 [term-signal-issue.zeek] - 1361916155.953494    40=len packet=4
1594228173.468123 [term-signal-issue.zeek] - 1361916155.954332   153=len packet=5
```

Examine last few errors:

```
$ egrep --before-context=1 --after-context=1 "(termination signal|error)" run-term-signal-issue/timestamp-zeek.log | tail -11
--
1594230200.390124 [term-signal-issue.zeek] - 1361916160.126052    40=len packet=11261
1361916160.126168 expression error in ./../term-signal-issue.zeek, line 6: field value missing (p$ip)
1594230200.390268 [term-signal-issue.zeek] - 1361916160.126636   451=len packet=11263
--
1594230200.436803 [term-signal-issue.zeek] - 1361916160.432432   153=len packet=12087
1361916160.432710 expression error in ./../term-signal-issue.zeek, line 6: field value missing (p$ip)
1594230200.436906 [term-signal-issue.zeek] - 1361916160.433857    52=len packet=12089
--
1594230200.499999 [term-signal-issue.zeek] - 1361916160.954049   904=len packet=13382
1361916160.954049 received termination signal
```

**Comment by jsiwek** [comment] 2020-07-08 22:56
> **The default Zeek functionality:**
> 
> If Zeek is reading from a live NIC then errors and signal log lines will be prefixed by current time.
> 
> However, if Zeek is reading from a PCAP /trace file then errors and signal log lines will be prefixed by network time.

That doesn't sound like the default behavior, it should emit network-time in either case.  (When reading live, network-time does tend to be very close to current-time, though)

> Is there a way to get Zeek to output errors and signal notification _always_ prefixed with current time instead of network time?

Not that I know without patching (but if you really did only want to alter stderr from Reporter alone and not all-logs-in-general, that's not a complex patch/option).

> Is there a way to get Zeek to output extra info too, e.g. PID and/or TID info, and network time in addition to current time?

There's a `getpid()` function you can call anywhere and include in you own`print`.  If you want to customize Reporter output, there's events like `reporter_info`, `reporter_error`, etc. that you can use to intercept, reformat, and spit back out (perhaps to separate, custom file).

> Is there a way to change the seemingly hard-coded output format of `PLUGIN_DBG_LOG()` so that it can be compatible style-wise with logging elsewhere?

Not that I know without patching.

> Is there a way to get multiple Zeek processes to automatically merge their debug log output into a single output file without having to log each instance to its own file and then attempt to merge the files after the instances have ended?

Not that I know, `debug.log` doesn't go through the standard log framework, it's writing straight to the file. There's likely always going to be a desire for this mode of operation: if we tried to merge via an IPC mechanism and then wanted to debug a breakage in that mechanism itself through `debug.log`, you'd be out of luck.

> But if trying to combine multiple Zeek output files then it becomes difficult to merge them into a single log of events at run-time. Whereas, if they were all prefixed with current time then you could just sort them together :-)

Maybe a simpler thing to do, at least to solve your "merging/sorting" requirement, is just change your `print` output to place `network_time()` first instead of `current_time()` since that's what reporter/debug/logs-in-general do.

**Comment by simonhf** [comment] 2020-07-08 23:21
> Maybe a simpler thing to do, at least to solve your "merging/sorting" requirement, is just change your `print` output to place `network_time()` first instead of `current_time()` since that's what reporter/debug/logs-in-general do.

Thanks for the suggestion, but the problem is that if I do that then I'd end up with lots of identical  timestamps because the network time only increments every time there is a new packet. So let's say I'd have n lines of debug log output generated by code I'm debugging in-between 2 packets; they'd all have the same network time. This can be illustrated as follows by running the above example but with this updated Zeek script which duplicates the same log line 3 times:

```
$ cat term-signal-issue.zeek 
global stderr = open("/dev/stderr");
global packet_count = 0;

event new_packet(c: connection, p: pkt_hdr) {
    packet_count += 1;
    print stderr, fmt("%f [%-21s] - %f %5d=len packet=%d", current_time(), @FILENAME, network_time(), p$ip$len, packet_count);
    print stderr, fmt("%f [%-21s] - %f %5d=len packet=%d", current_time(), @FILENAME, network_time(), p$ip$len, packet_count);
    print stderr, fmt("%f [%-21s] - %f %5d=len packet=%d", current_time(), @FILENAME, network_time(), p$ip$len, packet_count);
}
```

Run Zeek with the updated Zeek script:

```
$ cat term-signal-issue.zeek 
global stderr = open("/dev/stderr");
global packet_count = 0;

event new_packet(c: connection, p: pkt_hdr) {
    packet_count += 1;
    print stderr, fmt("%f [%-21s] - %f %5d=len packet=%d", current_time(), @FILENAME, network_time(), p$ip$len, packet_count);
    print stderr, fmt("%f [%-21s] - %f %5d=len packet=%d", current_time(), @FILENAME, network_time(), p$ip$len, packet_count);
    print stderr, fmt("%f [%-21s] - %f %5d=len packet=%d", current_time(), @FILENAME, network_time(), p$ip$len, packet_count);
}
...
+ sleep 1
+ kill -INT 107151
+ wait 107151
```

Examine head of Zeek stderr output:

```
$ cat run-term-signal-issue/timestamp-zeek.log | head
1594249420.354185 [term-signal-issue.zeek] - 1361916155.953172  1154=len packet=1
1594249420.354221 [term-signal-issue.zeek] - 1361916155.953172  1154=len packet=1
1594249420.354234 [term-signal-issue.zeek] - 1361916155.953172  1154=len packet=1
1594249420.354263 [term-signal-issue.zeek] - 1361916155.953222  1154=len packet=2
1594249420.354272 [term-signal-issue.zeek] - 1361916155.953222  1154=len packet=2
1594249420.354280 [term-signal-issue.zeek] - 1361916155.953222  1154=len packet=2
1594249420.354300 [term-signal-issue.zeek] - 1361916155.953222    80=len packet=3
1594249420.354310 [term-signal-issue.zeek] - 1361916155.953222    80=len packet=3
1594249420.354317 [term-signal-issue.zeek] - 1361916155.953222    80=len packet=3
1594249420.354483 [term-signal-issue.zeek] - 1361916155.953494    40=len packet=4
```

As you can see, the current time ticks up for each and every log line as expected. But the network time only ticks up once per packet new PCAP / trace packet, and not even that if multiple packets have the same timestamp (as coincidentally in the above example)... :-)

I'm new to Zeek... It could be that most Zeek users don't use PCAP / trace files. And of the ones who do, most of them don't care about multi process debugging. I might be in a very small crowd of people who have run into this? Would be great to hear from anybody else who has wanted to debug Zeek via logging... if anybody! :-)

**Comment by 0xxon** [comment] 2020-07-09 03:00
Whenever I did multi-process debugging I actually wanted per-process log-files - and I did examine them individually. From what I know you are the first person ever that cared about merging this kind of output.

And I agree with Jon - having something like IPC feels quite out-of-scope. debug.log is supposed to basically go out as directly as possible - since it typically is used when debugging quite low-level problems.

For single-node debugging - is there a problem with several times having the same timestamp? You still should get the output in the right order.

**Comment by simonhf** [comment] 2020-07-09 18:18
> Whenever I did multi-process debugging I actually wanted per-process log-files - and I did examine them individually. From what I know you are the first person ever that cared about merging this kind of output.

I guess it depends what type of multi process debugging is going on? The lower level it gets, the more you want to pore over the output log(s) with accurate timestamps? Maybe I'm too lazy, but it would just drive me crazy going backwards and forwards examining multiple logs all the time :-) And the more logs there are means more context switching for the developer...

> And I agree with Jon - having something like IPC feels quite out-of-scope. debug.log is supposed to basically go out as directly as possible - since it typically is used when debugging quite low-level problems.

Hmmm... maybe if the log output was held in shared memory it would be faster and safer? Why? Because the regular I/O in (some say bloated and slow) glibc does a lot of buffering in RAM, which means that if a process crashes then the last part of the log may be lost. Alternatively, one can force the output to be written immediately in which case there is a performance penalty to pay while the host application waits for the non-buffered write to happen. With a shared memory solution then even if the process crashes then the log output in shared memory lives on. A separate process may asynchronously output the log lines in shared memory using the O_DIRECT flag so that the Linux page cache is not churned upon writing (much larger output logs), thus helping with overall system file stability.

Reading the comment from Jon about IPC then I had the impression he is mostly anxious about the quality of the IPC mechanism and how to debug it if necessary, and not the idea of the IPC mechanism itself. Of course, I hope I'm not putting words into his mouth, so please forgive me and correct me if I misinterpreted the comments! :-) Having written such a shared memory logging mechanism myself a couple of times in the past, then I can confirm that they can end up much more efficient and faster, and it's usually necessary to create a special debugging mechanism just for debugging the shared memory log mechanism. But assuming there are enough automated tests etc, then there's no reason why such a mechanism should be unreliable. For example, such code at an ex-employer is processing trillions of log lines per month in production without error.

[1] https://unix.stackexchange.com/questions/258052/does-the-o-direct-flag-bypass-the-linux-page-cache-when-accessing-block-devices

> For single-node debugging - is there a problem with several times having the same timestamp? You still should get the output in the right order.

Often with debug log mechanisms it's possible to specific some kind of verbosity either at compile time and/or run-time. And sometimes it's possible to specify a verbosity for individual process components such as a plugin or a library, etc. The higher the verbosity then the more log lines, and run-time performance gets slower. And the lower the verbosity then the less log lines, and the closer the performance gets to run-time performance without debug logging. So it's useful for a developer to constantly have differing and accurate timestamps 'in their face' in the log. In this way, as time goes on, they get to 'learn' the speed of parts of the code without having to go to the trouble of specialized performance profiling, etc. A bit like if you live in a foreign country and just pick up the language on the fly without taking special classes :-) So "is there a problem"? Only in the sense that it's a potential missed opportunity to provide an extra level of (performance) awareness to the developer, which over time the Zeek project could profit from?

**Comment by jsiwek** [comment] 2020-07-09 18:27
> As you can see, the current time ticks up for each and every log line as expected. But the network time only ticks up once per packet new PCAP / trace packet, and not even that if multiple packets have the same timestamp (as coincidentally in the above example)... :-)

Within a process, it will still be output in order-of-execution.  For merging across many, you also still do have both network-time and current-time, so not sure what is preventing the merge/sort logic from using current-time if that's what you need.  If the issue is that pre-existing logs don't have a field containing current time, you can add it:

```zeek
# test.zeek
redef record Conn::Info += {
	cur_ts: time &log &default=current_time();
};

redef record Reporter::Info += {
	cur_ts: time &log &default=current_time();
};
```

```
$ zeek -B dpd -r bigFlows.pcap LogAscii::use_json=T ./test.zeek 
^C1361916162.518082 <params>, line 1: received termination signal

$ tail -n1 debug.log 
1361916162.518082/1594317728.925526 [dpd] NTLM[4013] EndOfData(F)

$ tail -n1 conn.log  | jq -r '[.ts,.cur_ts] | join("/")'
1361916157.822201/1594317728.916384

$ tail -n1 reporter.log  | jq -r '[.ts,.cur_ts] | join("/")'
1361916162.518082/1594317728.594842
```

**Comment by simonhf** [comment] 2020-07-10 16:35
Thanks for the tip, but in the Zeek script presented above the output goes to stderr, although the errors and signal warning go to both stderr and `reporter.log`:

```
$ cat run-term-signal-issue/reporter.log   
...
1361916156.125919       Reporter::ERROR field value missing (p$ip)      ./../term-signal-issue.zeek, line 6
1361916156.431484       Reporter::ERROR field value missing (p$ip)      ./../term-signal-issue.zeek, line 6
1361916156.572050       Reporter::ERROR field value missing (p$ip)      ./../term-signal-issue.zeek, line 6
1361916157.953214       Reporter::ERROR field value missing (p$ip)      ./../term-signal-issue.zeek, line 6
1361916158.570023       Reporter::ERROR field value missing (p$ip)      ./../term-signal-issue.zeek, line 6
1361916158.878293       Reporter::ERROR field value missing (p$ip)      ./../term-signal-issue.zeek, line 6
1361916158.955681       Reporter::ERROR field value missing (p$ip)      ./../term-signal-issue.zeek, line 6
1361916159.572137       Reporter::INFO  received termination signal     (empty)
...
```

Is there a way to add current time to the stdout / stderr output, like in the example you gave for adding it to log files?

**Comment by jsiwek** [comment] 2020-07-10 18:35
> Is there a way to add current time to the stdout / stderr output, like in the example you gave for adding it to log files?

Yeah, see if suppressing Reporter stderr and handling it yourself can do what you'd like:

```zeek
global stderr = open("/dev/stderr");
global packet_count = 0;

redef Reporter::info_to_stderr=F;
redef Reporter::warnings_to_stderr=F;
redef Reporter::errors_to_stderr=F;

event new_packet(c: connection, p: pkt_hdr) {
    packet_count += 1;
    print stderr, fmt("%f [%-21s] - %f %5d=len packet=%d", current_time(), @FILENAME, network_time(), p$ip$len, packet_count);
    print stderr, fmt("%f [%-21s] - %f %5d=len packet=%d", current_time(), @FILENAME, network_time(), p$ip$len, packet_count);
    print stderr, fmt("%f [%-21s] - %f %5d=len packet=%d", current_time(), @FILENAME, network_time(), p$ip$len, packet_count);
}

event reporter_info(t: time, msg: string, location: string) &priority=-5 {
    print stderr, fmt("%f [%-21s] - %f INFO %s, %s", current_time(), @FILENAME, network_time(), msg, location);
}

event reporter_warning(t: time, msg: string, location: string) &priority=-5 {
    print stderr, fmt("%f [%-21s] - %f WARNING %s, %s", current_time(), @FILENAME, network_time(), msg, location);
}

event reporter_error(t: time, msg: string, location: string) &priority=-5 {
    print stderr, fmt("%f [%-21s] - %f ERROR %s, %s", current_time(), @FILENAME, network_time(), msg, location);
}
```

**Comment by simonhf** [comment] 2020-07-10 21:58
Thanks! Although somewhat verbose, that's exactly what I wanted; current time now first, with network time later:

```
$ egrep --before-context=1 --after-context=1 "(termination signal|ERROR)" run-term-signal-issue/timestamp-zeek.log | tail -11     
--
1594417820.470439 [term-signal-issue.zeek] - 1361916160.126052    40=len packet=11261
1594417820.470554 [term-signal-issue.zeek] - 1361916160.126168 ERROR field value missing (p$ip), ./../term-signal-issue.zeek, line 22
1594417820.470630 [term-signal-issue.zeek] - 1361916160.126636   451=len packet=11263
--
1594417820.519796 [term-signal-issue.zeek] - 1361916160.432432   153=len packet=12087
1594417820.519888 [term-signal-issue.zeek] - 1361916160.432710 ERROR field value missing (p$ip), ./../term-signal-issue.zeek, line 22
1594417820.519915 [term-signal-issue.zeek] - 1361916160.433857    52=len packet=12089
--
1594417820.551989 [term-signal-issue.zeek] - 1361916160.609965    40=len packet=12664
1594417820.552091 [term-signal-issue.zeek] - 1361916160.609965 INFO received termination signal, 
```

**Comment by simonhf** [comment] 2020-07-10 22:18
Follow on newbie question:

It's great that this script info / warning / error output format can be redefined. Is it possible to do the same with the C/C++ plugin macro `PLUGIN_DBG_LOG()` output format?

**Comment by rsmmr** [comment] 2020-08-13 10:28
No, `PLUGIN_DBG_LOG` is hardcoded.

 I'll close this as it seems there's a workaround, and no immediate action item / pressing need  for a more complex solution.

**Closed by rsmmr** 2020-08-13 10:28 UTC
