### ISSUE TITLE
zeek 5.0.4 vs python 3.11

### ISSUE THREAD

**Issue by leres** [zeek/zeek#2654] opened 2022-12-14 22:22 UTC
I tried building the FreeBSD zeek port with python 3.11 and got a bunch of errors. I've attached a build log that shows the errors ([zeek-5.0.4.log.gz](https://github.com/zeek/zeek/files/10232072/zeek-5.0.4.log.gz)), here is an example error:
```
In file included from /wrkdirs/usr/ports/security/zeek/work/zeek-5.0.4/auxil/broker/bindings/python/enums.cpp:8:
In file included from /wrkdirs/usr/ports/security/zeek/work/zeek-5.0.4/auxil/broker/bindings/python/3rdparty/pybind11/include/pybind11/pybind11.h:45:
In file included from /wrkdirs/usr/ports/security/zeek/work/zeek-5.0.4/auxil/broker/bindings/python/3rdparty/pybind11/include/pybind11/attr.h:13:
/wrkdirs/usr/ports/security/zeek/work/zeek-5.0.4/auxil/broker/bindings/python/3rdparty/pybind11/include/pybind11/cast.h:446:36: error: member access into incomplete typ
e 'PyFrameObject' (aka '_frame')
                "  " + handle(frame->f_code->co_filename).cast<std::string>() +
                                   ^
/usr/local/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
typedef struct _frame PyFrameObject;
               ^
```

**Comment by ckreibich** [comment] 2022-12-14 23:08
I can confirm this over here, Fedora 37, also Python 3.11. Looks like it's the pybind version, which we've bumped in the meantime as part of upgrading Broker. I think you won't see this problem on Zeek's `release/5.1` branch.

**Comment by leres** [comment] 2022-12-14 23:15
> I can confirm this over here, Fedora 37, also Python 3.11. Looks like it's the pybind version, which we've bumped in the meantime as part of upgrading Broker. I think you won't see this problem on Zeek's `release/5.1` branch.

I plan on keeping the FreeBSD port on the LTS train, will 5.0 ever get the fix? If not it appears 5.0.4 bundles ypbind11 2.6.1, what version would be recommended?

**Comment by ckreibich** [comment] 2022-12-14 23:25
> will 5.0 ever get the fix

Yes certainly Craig, we'll need to fix this. I'm bummed because if we'd thought to backport recent CI upgrades from master to `release/5.0` immediately, we'd have pre-empted your ticket. :-)

If you're willing to work around it for now, I'd recommend 5.1.1.

**Comment by leres** [comment] 2022-12-14 23:30
> If you're willing to work around it for now, I'd recommend 5.1.1.

There are other ports that are giving me issues with python 3.11 but am investigating what it would take to make zeek 5.0.4 work, I might try removing the bundled pybind11 and using the FreeBSD port (which is current 2.10.0, the same as is bundled with 5.1.1).

**Comment by ckreibich** [comment] 2023-01-11 22:18
@leres I'm closing this since 5.0.5 is now out, which resolved this. If you still have trouble with that, please let us know. Thanks!

**Closed by ckreibich** 2023-01-11 22:18 UTC
Labels: Type: Bug :bug:, Type: Maintenance, Area: Broker

**Comment by leres** [comment] 2023-01-11 22:29
Thanks for the fix! I updated the port on Monday but it takes a little bit of work to test against python 3.11 and I haven't had time to do that yet.
