### ISSUE TITLE
Trailing semicolon in script erroneously reports syntax error on the next script

### ISSUE THREAD

**Issue by ynadji** [zeek/zeek#3784] opened 2024-06-13 18:03 UTC
Title says it all really. It's obviously a syntax error, however, on a system with a lot of packages it doesn't indicate exactly where the syntax error is. Same issue also happens when `@load`ing.

See below for a minimal example:

```ruby
yacin@sif ~ sif*
¡ zeek --version
zeek version 7.0.0-dev.254

yacin@sif ~ sif*
¡ cat foo.zeek 
event zeek_init()
	{
        print "dame mas";
        };

yacin@sif ~ sif*
¡ cat bar.zeek 
event zeek_init()
	{
        print "gasolina";
        }

yacin@sif ~ sif*
¡ zeek foo.zeek 
dame mas

yacin@sif ~ sif*
¡ zeek bar.zeek 
gasolina

yacin@sif ~ sif*
¡ zeek foo.zeek bar.zeek 
error in ./bar.zeek, line 2: syntax error, at or near "{"
```

**Comment by JustinAzoff** [comment] 2024-06-13 18:48
Yeah.. this can give some surprising results...

```
❯ head -n 10 a.zeek b.zeek 
==> a.zeek <==
event zeek_init(

==> b.zeek <==
) {
	print "hi!";
}
❯ zeek a b       
hi!```

**Comment by bbannier** [comment] 2024-06-13 18:56
This is a closely related or a duplicate of #3265, both have the same underlying reason (basically: [file loading](https://github.com/zeek/zeek/blob/345fc31dcc0ff08ace9fa3d227a8d975707ab44b/src/scan.l#L445-L452) already happening before any parsing which makes emitting diagnostics interesting).

**Comment by awelzel** [comment] 2024-06-17 07:54
Duplicate of #3265

**Closed by awelzel** 2024-06-17 07:54 UTC
