### ISSUE TITLE
OpaqueVal.h has too many classes in it

### ISSUE THREAD

**Issue by sethhall** [zeek/zeek#1180] opened 2020-09-22 20:17 UTC
OpaqueVal.h includes digest.h which includes openssl/md5.h which means that any plugins with include opaquevals needs to have openssl/md5.h available.

**Comment by jsiwek** [comment] 2020-09-23 00:12
Can you elaborate what the problem is and what you're asking for?

OpenSSL-header availability is a requirement of building Zeek from source and it's convenient if plugin build-environments generally have to abide similar requirements.  E.g. we might restructure just OpaqueVal.h to avoid inclusion of OpenSSL headers, but not sure what enforces it stays that way unless adopting a rigorous stance/policy of "Zeek headers must not include any OpenSSL header".  Also raises the question if other required dependencies like zlib & libpcap warrant similar treatment.

**Comment by sethhall** [comment] 2020-09-23 13:28
Yeah, I avoided the problem by making the plugin I'm working on just find OpenSSL and I think that's probably an ok approach although it does seem like it might be better to have all of the builtin opaque types implemented in a separate file from the OpaqueVal definition.

I am running into another problem now (related to the same problem) where the paraglob header file can't be found.

```
/usr/local/zeek/include/zeek/OpaqueVal.h:9:10: fatal error: 'paraglob/paraglob.h' file not found
#include "paraglob/paraglob.h"
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

I'm not really sure what steps I should take to fix or avoid this problem in the plugin without directly adding `/usr/local/zeek/include/` to my include path.

**Comment by sethhall** [comment] 2020-09-23 13:40
Now that I'm digging some more, I'm getting the sense that `/usr/local/zeek/include/` should have already been in my include path.  Am I possibly doing something wrong in the build system for the plugin that it isn't being included already?

**Comment by vpax** [comment] 2020-09-23 16:21
Yeah, I had to hack around this too for a plugin I was making.  Wound up making my own copy of `OpaqueVal.h`, not pretty.  I like the notion of splitting it into base class and then the set of derived classes that come with Zeek.

**Comment by jsiwek** [comment] 2020-09-23 17:23
> Now that I'm digging some more, I'm getting the sense that `/usr/local/zeek/include/` should have already been in my include path. Am I possibly doing something wrong in the build system for the plugin that it isn't being included already?

Also think that Zeek include path should have already been set up for you.  Do you have an example plugin and commands to reproduce what you see?  Or show output of the plugin's `./configure && make VERBOSE=1` ?  Most modern `configure` scripts should be asking for `zeek-config --include_dir` which usually has `/usr/local/zeek/include/` in it (maybe the `configure` script is from a very old plugin template/skeleton ?)

For the original question of what to do w/ `OpaqueVal.h` and dependency-library-header-handling: I agree it's maybe better to re-organize `OpaqueVal.h`, but that better-ness may be temporary unless the root problem is further addressed to prevent someone in the future from deciding to include an OpenSSL header in a Zeek header without being aware of this discussion and how that may be "bad".  A couple options:

1. Make it a general development policy that we don't include external/dependency headers from Zeek headers

2. Extend the `ZeekPlugin*.cmake` logic that gets included by default in plugins to replicate some of Zeek's own dependency-finding logic (e.g. openssl, libpcap, zlib) so that it can try to automatically set up include paths for any that are found.

Thinking (2) is a decent way, but it does still mean that plugin build-environments may require various external-dependency headers are installed somewhere.

**Comment by sethhall** [comment] 2020-09-24 14:54
I'm updating Jan's Lognorm plugin (https://github.com/J-Gras/bro-lognorm) and I think that I've updated to all of the latest stuff in it, but I'll double check that.

Would we be able to create some sort of test that would verify that no non-Zeek headers are included from Zeek "API" headers?  I'm only asking because I'm not actually sure how we'd accomplish that.

**Comment by sethhall** [comment] 2020-09-24 15:02
Yep, ignore my comment about the include directory not being found.  I had updated the configure script in the plugin, but apparently to not quite a new enough version.  I updated to the current version and it works fine.

**Comment by jsiwek** [comment] 2020-09-24 20:20
> Would we be able to create some sort of test that would verify that no non-Zeek headers are included from Zeek "API" headers?

I don't know either, but I think the root problem is better solved with additional CMake and `zeek-config` logic like #1190.  I set that to close this issue, but if people still want to re-organize `OpaqueVal.h` for another reason, just say so and this can stay open for that.

**Closed** 2020-10-02 17:51 UTC
Labels: Area: Build/Platform, Area: Plugins, Type: Enhancement, Type: Maintenance
