### ISSUE TITLE
can't  reassemble entire packet when get [tcp acked unseen segment]

### ISSUE THREAD

**Issue by linpengstc** [zeek/zeek#335] opened 2019-04-12 09:57 UTC
When analyse traffic mirror, I always get the content_gap event and zeek will  not reassemble the entire package.
I think the reason is the ACK arrived before the the data package,

![image](https://user-images.githubusercontent.com/3882453/56028602-17847d80-5d4b-11e9-99b2-a10d27ddab25.png)
When I analyse the pcap in wireshark, I can see the a ACK marked as [TCP ACKed unseen segment]. Wireshark can reassemble the  entire http package, but bro can't
[pcap.zip](https://github.com/zeek/zeek/files/3072781/pcap.zip)

I provide my pcap and bro script,  run  `bro -r  http_pkg7   http_header.bro`

![image](https://user-images.githubusercontent.com/3882453/56030377-469cee00-5d4f-11e9-9e45-a41eb66614d8.png)

**Comment by jsiwek** [comment] 2019-04-15 19:01
There's two bits of info that are relevant here:

1. The TCP reassembly process in Zeek/Bro always moves forward and adjusts expectations based on the ACKs it sees.  If an ACK is seen before the opposite TCP's associated data, then that is treated as a content gap at the moment the ACK is seen and that space in the global sequence is considered as being analyzed already.  Any further data seen in the already-analyzed sequence space is just discarded.

2. The HTTP analyzer isn't particularly resilient to content gaps.  If it gets a content gap that is not entirely contained within an HTTP message body, it will not attempt to re-synchronize and analyze any further content.

Point (1) is more relevant than (2) here because this particular pcap doesn't have further content, but I mention it just in case you do run into it.  I think both issues are non-trivial to address anytime soon:

To better deal with (1) we'd likely need more buffering mechanisms in the TCP reassembly process to understand the past reassembly history/state and delay reporting gaps -- maybe not a great thing to add to a system aimed more at real-time analysis.  Ideally, the capture setup would would show us the data before the associated ACKs of that data.

Improvements to (2) likely won't happen until HTTP/MIME analyzers get re-written.  You may be able to find some use in detecting this type of problem via the `http_message_done` event's `http_message_stat` parameter, which has an `interrupted` field that is true if a content gap interrupted the analysis.

**Comment by piotrpww** [comment] 2019-04-23 12:13
I have the same problem, which unfortunately leads to lose HTTP data that is send between client and server, and zeek is unable to parse payload that the client send to the server. 
If the http server has sent "TCP ACKed unseen segment" to the client, it starts to retransmit pointed data. After that Zeek generates "content gap" event and discards further data. I think that this is security breech, because at last data is sent to the server and Zeek does not analyse the data, as it is automatically discarded. 
![zeek_does_not_parse_http_retransmit](https://user-images.githubusercontent.com/33134576/56578722-9d67ba80-65ce-11e9-8267-715d0794262e.png)


I tried to debug the problem, and turned on DEBUG in sourcecode and write simple script as follows:

event tcp_packet(c: connection , is_orig: bool , flags: string , seq: count , ack: count , len: count , payload: string ) &priority=-5
{
if ( is_orig && c?$http && c$http?$method && c$http$method == "POST" && c$http$uri == "XXXXXXXXXXXXXXXXXXXX" )
{
print "----------------------------TCP_BEGIN";
print c$http$uri;
print c$http$method;
print c$http$host;
print "tcp payload:";
print payload;
print "############################TCP_END";
}

and then run Zeek. The output is as follows:
![zeek_does_not_analyse](https://user-images.githubusercontent.com/33134576/56579847-7fe82000-65d1-11e9-80e1-c7f45d158882.png)

**Comment by piotrpww** [comment] 2019-04-23 13:20
@jsiwek is there any possibility to tell zeek to append next retransmitted tcp segment to http message?

**Comment by piotrpww** [comment] 2019-04-25 05:59
My problem is solved :) It was caused by network adapter. After the NIC driver was reinstalled and PF_RING ZeroCopy was used Zeek/BRO is receiving packet in a correct way. Packets presented by pf_ring without a ZC and with multiple queues were in other order than they arrive at network interface.

**Comment by linpengstc** [comment] 2019-05-14 02:27
My problem maybe also solved when I install PF_RING and execute ethtool -K eth0 gro off.  It seems work well and the content gap didn't happen.

**Comment by jsiwek** [comment] 2019-05-14 16:38
Thanks for reporting back solution(s), I'll close this as solved via improving capture setup.

**Closed by jsiwek** 2019-05-14 16:38 UTC
Labels: Area: Packet Capture, Area: Protocol Analysis
