### ISSUE TITLE
Move UDP/TCP/ICMP to packet analyzers

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#1114] opened 2020-08-12 10:00 UTC
Once we have #248, #910, and #284, I believe we should be able to move UDP/TCP/ICMP to packet analyzers as well.

**Comment by timwoj** [comment] 2020-10-30 14:55
Moving this to the 4.1.0 milestone since it's not going to happen for 4.0.

**Comment by timwoj** [comment] 2021-01-29 19:45
@rsmmr and I have talked about this a bit, and I'm pretty sure that this work can be done before #284.

**Comment by timwoj** [comment] 2021-03-04 17:52
I've been chipping away at this for a bit. Here's some notes and a pile of questions.

General Design:

- Create a new abstract "IPBasedAnalyzer" class that IP-based packet analyzers can inherit from
   - Move/adapt a bunch of code from NetSession::ProcessTransportLayer and other methods into this class
   - This class would be responsible for calling into `Conn` to flow into the session analyzers
- Create new packet analysis plugins for each of the protocols inheriting from the above
- Modify the IP plugin to call the new plugins as the next analyzer
- Move packet dumping code out of NetSessions::ProcessTransportLayer into the IP plugin (?)
- Modify NetSessions to basically be a manager of session objects (see below)
  - Store one map of sessions instead of three for the differing transport protocols

Connections:

- Create new base class that gets stored by session manager called Session, containing the following:
    - Timers
    - Packet recording state
    - Hashed key value
    - Eventing (Event(), EnqueueEvent(), pure virtual(?))
    - Cleanup (Done(), pure virtual)
- Existing Connection class would only support IP-based connections
    - Probably needs to be renamed, but renaming it would break existing code
    - Existing ConnIDKey object gets stored here, if needed. A hashed version of it will be stored by the parent.

Big questions:

- What about all of the places that call NetSessions methods and pass a connection, if ConnIDKey is different than it used to be?
- Can anything move out of the existing TCP analyzer in the sessions tree?
- It bugs me that the stepping stone manager is part of NetSessions. Why is it not just part of the stepping stone analyzer?
- How do statistics work? Currently we store them with the sessions, but the new architecture wouldn’t separate them by protocol type.

Future-work Ponderings: 
- Can we make the assumption that the existing protocol tree only ever gets called from IP-based packets?
- Is it possible to support TCP/UDP without inheriting from IP? ICMP requires IP as a base protocol, but TCP and UDP don’t. Would anyone even use that if we did support it?
- Register two “child” analyzers of the main analyzer and switch on the two based on whether the packet has an ip_hdr filled in?

**Comment by rsmmr** [comment] 2021-03-05 08:11
Taking a stab at some answers/thoughts:

> General Design:

Sounds good, I like this.

> * Create a new abstract "IPBasedAnalyzer" class that IP-based packet analyzers can inherit from

Would be helpful to establish  a naming scheme for base classes that other analyzers are built on top of. We have the `TCP_ApplicationAnalyzer` already, which was never very intuitive; and we'll probably get more. Maybe it's just that "Based" (``TCPBasedAnalyzer``) though that doesn't feel quite smooth to me.

> * Move packet dumping code out of NetSessions::ProcessTransportLayer into the IP plugin (?)

Even further down I'd say, with interface from packet analyzers to say if they want a packet recorded.
 
> * Existing Connection class would only support IP-based connections   
>   * Probably needs to be renamed, but renaming it would break existing code

yeah, keeping the name and have it mean "something running on top of IP" seems fine to me. "Connection" then is always IP-based, and "Session" is more generic.

> * What about all of the places that call NetSessions methods and pass a connection, if ConnIDKey is different than it used to be?

I only see 3 public methods in NetSessions that use `Connection` (FindConnection/Insert/Remove). Can we just switch them over to the new ConnIDKey & Session?

> * Can anything move out of the existing TCP analyzer in the sessions tree?

Can you elaborate what you refer to here? example would help

> * It bugs me that the stepping stone manager is part of NetSessions. Why is it not just part of the stepping stone analyzer?

Mostly historic but I think the one challenge is that it needs global state (its manager). If we can initialize that correctly out of the stepping stone analyzer itself, moving it over there sounds good to me.

> * How do statistics work? Currently we store them with the sessions, but the new architecture wouldn’t separate them by protocol type.

Can we move this over to the new Telemetry framework? Then each analyzer can collect what it deems appropriate. for For backwards compatibility in script-land, we could provide a new implementation of `get_conn_stats()` that pull from `Telemetry` (or we could just say this doesn't make sense anymore and remove that function altogether.).

> * Can we make the assumption that the existing protocol tree only ever gets called from IP-based packets?

At the transport-layer I'd say that is fine: While I can in principle see somebody wanting to, say, analyze TCP even if it's not coming over IP, the use cases for that seem so rare/unusual that I don't think it's worth putting in extra effort for it at this point. If this ever came up as something important to support, I'd rather tackle it separately at that point then building it in right now.

At the application layer, it seems more useful: being able to, say, analyze HTTP even if it doesn't come in through TCP/IP would be a nice-to-have.  That said, I wouldn't have a problem with likewise postponing this to some other point if it's easier to just ignore right now. Also, with Spicy parsers, it'll be easier to reuse them at other points in the protocol stack anyways as they don' have the current analyzer structure baked in.

> * Is it possible to support TCP/UDP without inheriting from IP? ICMP requires IP as a base protocol, but TCP and UDP don’t. Would anyone even use that if we did support it?

See above.

> * Register two “child” analyzers of the main analyzer and switch on the two based on whether the packet has an ip_hdr filled in?

Can you say more? Is this an idea or a potential requirement?

**Comment by timwoj** [comment] 2021-03-05 20:13
> I only see 3 public methods in NetSessions that use Connection (FindConnection/Insert/Remove). Can we just switch them over to the new ConnIDKey & Session?

I'm not sure. For example, `FindConnection` is used in the bifs of a few analyzers, which means it could be potentially used in external plugins. That said, we could leave the versions in there that take/return `Connection` objects, add new ones that take Sessions, and deprecated the old ones. I'd be ok with that setup.

> Can you elaborate what you refer to here? example would help

This one was me talking off the top of my head. I could see perhaps `TCPEndpoint` being useful, since the packet analyzer could go ahead and build it so later analyzers wouldn't have to. The question would be how to pass that down the analyzer chain though.

> Can we move this over to the new Telemetry framework?

Yah, that'd be great, actually.

> Can you say more? Is this an idea or a potential requirement?

That was me brainstorming how to do the non-IP TCP analyzer and have it fit into the existing packet analyzer framework.

**Comment by timwoj** [comment] 2021-03-11 16:57
> That said, we could leave the versions in there that take/return Connection objects, add new ones that take Sessions, and deprecated the old ones. I'd be ok with that setup.

After some further work, it looks like all that needs to stay for now is `FindConnection(Val*)` and `FindConnection(ConnIDKey, TransportProto)`. The `Insert` and `Remove` methods can take `Session` pointers instead and continue working as expected. I may be able to rework the two `FindConnection` methods, but I need to see how much they're used.

**Comment by timwoj** [comment] 2021-03-12 22:51
I just discovered an issue that I think might require a little rework: what happens in the case of UDP encapsulation, such as with AYIYA tunnels and the like? Right now, the new UDP analyzer dumps immediately into processing any payload as it always has through the session analyzers. 

Right now the way those tunnels work is we come out of the packet analyzers, into the session analyzers, then back out of them into the packet analyzers, strip the tunnel headers, and put the packet back into the session analyzers to process the rest. Ideally, tunnels are packet analyzers. We would pull the UDP header off the packet and forward them to the next analyzer, which might be a tunnel.

**Comment by rsmmr** [comment] 2021-03-15 09:58
> Ideally, tunnels are packet analyzers. We would pull the UDP header off the packet and forward them to the next analyzer, which might be a tunnel.

Yeah, that sounds right to me (at least for tunnels working packet-by-packet). I'm not familiar enough with the tunnel code anymore to say how much pain doing that would be?

**Comment by timwoj** [comment] 2021-03-31 18:17
For the discussion below, I'm calling the old analyzer system the "session analyzers" so as to differentiate from packet analyzers.

I think my biggest sticking point right now is how to handle forwarding out of the packet analyzers. The problem is that it can take two paths. In a typical packet analyzer, `packet_analysis::Analyzer::ForwardPacket` does a lookup to find the next analyzer based on some value (usually a protocol identifier), and falls back to a default analyzer if one is configured, or reports an unknown-protocol weird if it can't find something to forward to. With these new analyzers, there's a second path it can take, which is down into the session analyzers. For example, the ICMP analyzer has ConnSize as a child analyzer and the UDP analyzer has PIA.

I need to figure out how to handle this. One way would be to create a "dummy" analyzer that lives in the session analyzers that packet analyzers can set as their default. That way if the identifier-based lookup fails, it would fall back to calling into the that tree. If there's nothing to forward to, we'd continue returning the weird. That would require an API change for `analyzer::Analyzer::ForwardPacket`, since the current API doesn't return any sort of success or failure. It also requires me to figure out how to pass down the session analyzer through the `packet_analysis::Analyzer::ForwardPacket` call stack so it knows the right place to forward to.

**Comment by jsiwek** [comment] 2021-04-01 00:15
> With these new analyzers, there's a second path it can take, which is down into the session analyzers. For example, the ICMP analyzer has ConnSize as a child analyzer and the UDP analyzer has PIA.
> 
> I need to figure out how to handle this. One way would be to create a "dummy" analyzer that lives in the session analyzers that packet analyzers can set as their default. That way if the identifier-based lookup fails, it would fall back to calling into the that tree.

The idea of this is that the two paths have to be taken exclusively from each other ?  I actually think they may both always need to be taken.  That is, I expect changing transport-layer analyzers into packet-analyzers would provide an additional mechanism of how data may be forwarded into subsequent packet-analyzers, but the traditional analysis tree continues working the same as before.

For example, say there's now a packet-analyzer for UDP, it may allow someone to implement some types of tunnel-decapsulation as a packet-analyzer by speculating about an identifier it sees in the UDP payload, but if it matches by coincidence, it shouldn't prevent the traditional UDP analysis tree from processing things like it used to.

i.e. if changing these transport-protocols to be packet-analyzers has any code path that doesn't send the data through the traditional analysis tree (e.g. PIA), that's a breaking change of significance since Analyzers, which may be external/user-written, were never expecting to be bypassed due to packet-analysis mechanisms.

**Comment by timwoj** [comment] 2021-04-02 16:24
> The idea of this is that the two paths have to be taken exclusively from each other ? I actually think they may both always need to be taken. That is, I expect changing transport-layer analyzers into packet-analyzers would provide an additional mechanism of how data may be forwarded into subsequent packet-analyzers, but the traditional analysis tree continues working the same as before.

Hmm, that's a good point that they shouldn't be exclusive. The question then is how to handle the unknown-protocol reports from these analyzers. Should there be an option for an analyzer to suppress such reports? At that point, I could just call both ForwardPacket methods, and each side could figure out whether it needs to handle anything.

**Comment by jsiwek** [comment] 2021-04-02 17:06
> The question then is how to handle the unknown-protocol reports from these analyzers. Should there be an option for an analyzer to suppress such reports?

Think so since it's not as interesting when payload structure starts getting more arbitrary as it will in UDP/TCP and can typically already infer from existing info whether Zeek found an analyzer that understood what was inside (e.g. conn.log and "service" field).

**Comment by timwoj** [comment] 2021-04-12 18:20
I've been working on splitting this work apart into pieces to ease reviewing. I have most of the first PR ready to go, which is all of the Connection, Session, and SessionManager changes. There's two things worth mentioning with this prior to opening the PR:

1. It's about a 2.5% performance loss (235s vs 241s) on the file-reading benchmark. This is entirely due to the fact that session are stored keyed by a hash and the hashing of a `ConnIDKey` takes extra time. Previously we just stored and compared the `ConnIDKey`s as the key in the map.
2. Zeek is complaining about invalid TCP checksums sporadically during the benchmark runs. It's only happening in the `tcpreplay` runs, and it's definitely not every pass. I'm trying to track down what's happening there.

**Comment by timwoj** [comment] 2021-04-14 18:08
> It's about a 2.5% performance loss (235s vs 241s) on the file-reading benchmark. This is entirely due to the fact that sessions are stored keyed by a hash and the hashing of a ConnIDKey takes extra time. Previously we just stored and compared the ConnIDKeys as the key in the map.

I managed to reduce this to a 1-1.5% performance hit. The big reason is that we're building and hashing a `ConnIDKey` for every single packet. It was over-doing this a bit and hashing the same object repeatedly, but after fixing that I got the time down a bit. It's definitely still slower though.

**Comment by timwoj** [comment] 2021-04-21 17:59
@J-Gras brought up an interesting question on the PR for session management: https://github.com/zeek/zeek/pull/1516#issuecomment-824156834. The gist of the comment is whether it makes sense to continue having a central session manager. With the new packet analyzers for transport protocols, it's possible that we could move session management into those analyzers, and let each protocol handle their own sessions. This would reduce the possibility of collisions between session types, but could also potentially complicate the code around teardown of sessions at shutdown. 

I want to move that discussion over here to the issue so we can get to a consensus during the analyzer work and prior to that PR being filed.

**Comment by timwoj** [comment] 2021-06-02 21:52
This work is fully complete now. All three of the analyzers have been moved. There's a minor fix to add some deprecation warnings, but I'm going to go ahead and close this issue since I should have a PR for it momentarily.

**Closed by timwoj** 2021-06-02 21:52 UTC
Labels: Area: Plugins
