### ISSUE TITLE
ZAM script compilation 

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#1471] opened 2021-03-30 14:14 UTC
Compile Zeek scripts to the Zeek abstract machine.

@vpax can you provide a short summary here with the main outstanding todos?

We'll wait with this for #1470, I'll set the milestone to 4.2 for now.

**Comment by vpax** [comment] 2021-03-30 19:54
Main todos:
1. Rewrite templater in C++
2. Put together PR with main compilation functionality
3. Put together PR with low-level ZAM optimization
4. Decide whether we want to support ZAM save files.  If so, finalize file organization scheme and submit PR
5. Put together PR with documentation
6. Optional: add functionality to address language features that currently lead to skipping compilation (lambdas, `when` clauses)

I frame most of the above in terms of PR's since the development work is done, but needs to be ported because it has diverged from Zeek (and from how some of the previous stages wound up being changed for merging)

**Comment by 0xxon** [comment] 2022-01-04 09:10
Since, I think, the bulk of this is in Zeek now - do we perhaps want to replace this with a bug tracking the current status/plans? :)

**Comment by vpax** [comment] 2022-01-04 16:17
Makes sense to me.

**Comment by ckreibich** [comment] 2022-10-05 18:42
I'm closing this as per above discussion, also confirmed earlier today with Vern.

**Closed by ckreibich** 2022-10-05 18:42 UTC
Labels: Type: Enhancement, Area: Scripting
