### ISSUE TITLE
PF_RING ZC - Failed to register fd 22 from PktSrc: Bad address

### ISSUE THREAD

**Issue by tsqrd** [zeek/zeek#1157] opened 2020-09-04 14:10 UTC
I'm aware of the changes made in 3.1 and discussed in this [blog post](https://zeek.org/2020/04/03/the-new-io-loop-in-zeek-3-1/).  Since this change I have been unable to update zeek because we rely on pf_ring ZC and zbalance_ipc (load balancing).  I have compiled zeek with [libpcap that has zc support](https://github.com/ntop/PF_RING/tree/dev/userland/libpcap-1.9.1).

I realize this is likely a problem with [zbalance_ipc](https://github.com/ntop/PF_RING/blob/dev/userland/examples_zc/zbalance_ipc.c), but I'm looking for help with how to fix it so that it works with zeek > 3.1.

Version info:
CentOS Linux release 7.7.1908
zeek 3.3.0-dev.241
pfring-7.7.0-3160.x86_64
ixgbe-zc 5.5.3.3160-dkms

```
[root@server~]# zcount_ipc -c 10 -i 0
=========================
Absolute Stats: 65'273 pkts (0 drops) - 48'611'446 bytes
Actual Stats: 43'181.73 pps (0.00 drops) - 0.24 Gbps
=========================

```

```
[root@server~]# zeek -i zc:10@0
listening on zc:10@0

error: Failed to register fd 22 from PktSrc: Bad address
fatal error: Failed to register pktsrc fd with iosource_mgr
```

Using just pf_ring ZC without zbalance_ipc **works**, which leads me to believe the issue lies within [zbalance_ipc](https://github.com/ntop/PF_RING/blob/dev/userland/examples_zc/zbalance_ipc.c)
```
[root@server~]# zcount -i zc:eth1
=========================
Absolute Stats: 3'353'880 pkts (0 drops) - 2'489'825'502 bytes
Actual Stats: 1'678'156.94 pps (0.00 drops) - 9.94 Gbps
=========================
```

```
[root@server~]# zeek -i zc:eth1
listening on zc:eth1

1599228100.924088 1331766 packets received on interface zc:eth1, 5053850 (79.14%) dropped
```

**Comment by timwoj** [comment] 2020-09-04 17:33
This is a dupe of https://github.com/zeek/zeek/issues/1063. I'll copy/paste this info over there. From my testing, it looks like a bug in libkqueue. I opened an issue on their repo, but I haven't gotten any responses yet.

**Closed** 2020-09-04 17:33 UTC
